
from multiprocessing.managers import SyncManager
from random import random


import time


from ImageToFlowmap.networker_5 import *
from ImageToFlowmap.ui_Parameter import *
#from logger import *

import sys, pickle
from multiprocessing import Process, Queue, Manager

#addlog("debug", f"✅ Start of {sys.modules[__name__].__file__}!")
from PySide6.QtWidgets import QApplication, QStyleFactory, QTableWidget, QMainWindow, QTableWidgetItem, QVBoxLayout, QLineEdit, QDialog, QScrollBar
from PySide6.QtCore import QTimer, Qt, QTimer
from PySide6 import QtGui
from settings import *

import networker_5 as networker

# for windows dialoge
import subprocess

## UI Class because ui_ImageToFlowmap is generated by qt designer and will be overwritten by design changes
from OpenGL.GL import *
from OpenGL.GLU import *
from ui_ImageToFlowmap import Ui_ImageToFlowmap
from ui_Parameter import Ui_ParameterEdit
import regex as re
import copy

from functools import partial

from OpenGLHandler import MyGL, ImageLayer, PathLayer, PointLayer, FlowmapLayer, pointcolor, linecolor

networker.set_Accessmanager()

class FlowMapGenFiles():
    def __init__(self, BaseImagePath : xfile):
        self.ClusterFile    : xfile = None
        self.Clusters       : xfile = None
        self.FlowMapFile    : xfile = None
        self.BaseFile = BaseImagePath
        self.SubBaseFolder = BaseImagePath.name.replace(BaseImagePath.format, "")
        self.gen_xfiles()

    def gen_xfiles(self):
        ##ClusterFile
        self.ClusterFile = copy.copy(self.BaseFile)
        self.ClusterFile.name = self.ClusterFile.name.replace(self.ClusterFile.format, "_Clusters.png")
        self.ClusterFile.format = ".png"
        self.ClusterFile.root = os.path.join(self.ClusterFile.root, self.SubBaseFolder)
        self.ClusterFile.fullname = os.path.join(self.ClusterFile.root, self.ClusterFile.name)
        ##NetworkFile
        self.Clusters = copy.copy(self.BaseFile)
        self.Clusters.name = self.Clusters.name.replace(self.Clusters.format, "_Clusters.pkl")
        self.Clusters.format = ".pkl"
        self.Clusters.root = os.path.join(self.Clusters.root, self.SubBaseFolder)
        self.Clusters.fullname = os.path.join(self.Clusters.root, self.Clusters.name)
        ##FlowmapFile
        self.FlowMapFile = copy.copy(self.BaseFile)
        self.FlowMapFile.name = self.FlowMapFile.name.replace(self.FlowMapFile.format, "_Flowmap.png")
        self.FlowMapFile.format = ".png"
        self.FlowMapFile.root = os.path.join(self.FlowMapFile.root, self.SubBaseFolder)
        self.FlowMapFile.fullname = os.path.join(self.FlowMapFile.root, self.FlowMapFile.name)

class ManagerProcess:   #is instanced as subprocess
    def __init__(self, queuein : Queue, refreshrate = 10000):
        self.in_q = queuein   
        self.subprocesses = {}
        self.refreshrate = refreshrate
        self.terminatequeue = Queue()   
        self.lastupdate = time.time()
        self.notdead = True

    def setrefreshrate(self, ms : int):
        self.refreshrate = ms

    def run(self):
        while self.notdead:
            newtime = time.time()
            if not self.in_q.empty():
                a = self.in_q.get()
                if type(a) == dict:
                    if len(a) == 1:
                        k, i = list(a.items())[0]
                        if k == "set_refreshrate":
                            self.setrefreshrate(i)
                            continue
                        elif k == "stop":
                            self.stop()
                        elif k == "stop_workerprocesses":
                            self.stop_workerprocesses(i)
                elif newtime - self.lastupdate >= self.refreshrate / 1000:                    
                    fntype, fn, args = a
                    if fntype in self.subprocesses: # we kill old processes
                        self.stop_workerprocess(fntype)
                    self.subprocesses[fntype] = BetterProcess(Process(
                        target=fn,
                        args=tuple(*[args + [self.terminatequeue, fntype]])
                    ), TerminateQueue=self.terminatequeue)
                    self.subprocesses[fntype].Process.start()
                    self.lastupdate = newtime
                while not self.terminatequeue.empty():
                    fntype = self.terminatequeue.get()
                    self.stop_workerprocess(fntype)

    def get_process(self, fntype):
        if fntype in self.subprocesses:
            return self.subprocesses[fntype]
        return None
    
    def start(self):
        self.poll()

    def stop(self):
        self.stop_workerprocesses()
        self.notdead = False
        sys.exit()

    def stop_workerprocesses(self, WorkerProcessName : str = "", StopMultiple = True):
        tokill = []
        for k in self.subprocesses.keys():
            if WorkerProcessName in k:
                tokill.append(k)
                if not StopMultiple:
                    break
        for k in tokill:
            self.stop_workerprocess(k)
            

    def stop_workerprocess(self, ProcessType : processtypes):
        if ProcessType in self.subprocesses and hasattr(self.subprocesses[ProcessType], "Process"): #if None will skip
            if self.subprocesses[ProcessType].Process.is_alive():
                self.subprocesses[ProcessType].TerminateQueue.put(True)
                self.subprocesses[ProcessType].Process.join(timeout=1)
                if self.subprocesses[ProcessType].Process.is_alive():
                    self.subprocesses[ProcessType].Process.terminate()
            
            self.subprocesses[ProcessType].Process = None
            
            self.subprocesses[ProcessType].UpdateQueue = None
            self.subprocesses[ProcessType].TerminateQueue = None
            
            if self.subprocesses[ProcessType].QTimerUpdate: 
                self.stop_timer(self.subprocesses[ProcessType].QTimerUpdate)
                self.subprocesses[ProcessType].QTimerUpdate = None
            if self.subprocesses[ProcessType].QTimerTerminate:
                self.stop_timer(self.subprocesses[ProcessType].QTimerTerminate)
                self.subprocesses[ProcessType].QTimerTerminate = None
            self.subprocesses[ProcessType] = None
            del self.subprocesses[ProcessType]

class BetterProcess():
    def __init__(self, TheProcess : Optional[Process], QTimerUpdate : Optional[QTimer] = None, QTimerTerminate : Optional[QTimer] = None, UpdateQueue : Optional[Queue] = None, TerminateQueue : Optional[Queue] = None):
        super().__init__()
        self.Process            : Optional[Process] = TheProcess
        self.QTimerUpdate       : Optional[QTimer]  = QTimerUpdate
        self.QTimerTerminate    : Optional[QTimer]  = QTimerTerminate
        self.UpdateQueue        : Optional[Queue]   = UpdateQueue
        self.TerminateQueue     : Optional[Queue]   = TerminateQueue

    def start(self):
        if self.Process:
            self.Process.start()
            return True
        return False


class ImageToFlowmapUI(QMainWindow, Ui_ImageToFlowmap):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        
        self.processtypes = processtypes
                                                ####!!! The Queue for the process will get attached to it 
        self.parallelprocesses: Dict[processtypes, Optional[BetterProcess]] = {x : None for x in get_args(processtypes)}
        self.checkingprogress = False
        #self.init_managerprocess()

        self.SCRLB_MainImage_OverallSpeed.doubleSpinBox = self.doubleSpinBox_SCRLB_MainImage_OverallSpeed

        ##1. Folder
        self.Button_SelectFolder.clicked.connect(self.select_folder)
        
        ##2. Files
        self.table_SelectFiles.itemSelectionChanged.connect(self.file_selected)
        self.SCRLB_BaseImgAlpha.valueChanged.connect(self.baseimg_alpha_changed)

        ##3. ClusterMethod
        self.ClusterFolderName = "ClusterImages"
        self.comboBox_ClusterMethod.addItems(get_args(clustering_methods))
        self.comboBox_ClusterMethod.currentIndexChanged.connect(self.update_clustermethod)
        self.Button_ClusterMethodReload.pressed.connect(self.cluster_method_reload)
        self.Button_ClusterMethodParameters.pressed.connect(self.edit_cluster_method_parameters)
        self.SCRLB_ClusterAlpha.valueChanged.connect(self.cluster_alpha_changed)
        self.update_progressbar("Clustering",0)
        self.progressBar_ClusterMethod.setStyleSheet("""
                            QProgressBar {
                                border: 2px solid grey;
                                border-radius: 5px;
                                text-align: center;
                            }
                            QProgressBar::chunk {
                                background-color: orange;
                                width: 20px;
                            }
                            """)
        ##4. Clusters
        self.clusterobj : clusters
        self.table_SelectCluster.itemSelectionChanged.connect(self.cluster_selected)        

        ##5. Networks
        self.table_SelectNetwork.itemSelectionChanged.connect(self.network_selected)
        self.Button_NetworkGenerateAll.pressed.connect(self.network_generate_all)
        self.Button_NetworkGenerateParameters.pressed.connect(self.network_generate_parameters)
        #self.Button_NetworkGenerate.pressed.connect(self.network_split)
        #self.Button_NetworkSplitParameters.pressed.connect(self.network_split_parameters)

        ##6. Junctions
        self.table_SelectJunction.itemSelectionChanged.connect(self.junction_selected)
        self.SCRLB_JunctionAlpha.valueChanged.connect(self.junction_alpha_changed)
        self.table_SelectJunction.doubleClicked.connect(self.junction_selected_doubleclick)
        ##7. Paths
        self.table_SelectPath.itemSelectionChanged.connect(self.path_selected)
        self.table_SelectPath.doubleClicked.connect(self.path_selected_doubleclick)
        self.Button_PathDelete.clicked.connect(self.path_delete)
        self.SCRLB_PathAlpha.valueChanged.connect(self.path_alpha_changed)

        ##9. Flowmaps
        self.Button_FlowmapGenerateAll.clicked.connect(self.flowmap_generate_all)
        self.Button_FlowmapGenerateSelectedNetwork.clicked.connect(self.flowmap_generate_selected_network)
        self.Button_PanningTexture.clicked.connect(self.select_panningtexture)     
        self.progressBar_FlowmapGenerate.setMaximum(100*100)
        self.SCRLB_FlowmapAlpha.valueChanged.connect(self.flowmap_alpha_changed)
        self.doubleSpinBox_SCRLB_Panning_X.valueChanged.connect(self.panning_x_changed)
        self.doubleSpinBox_SCRLB_Panning_Y.valueChanged.connect(self.panning_y_changed)

        self.checkBox_DrawFlowmapColors.checkStateChanged.connect(self.checkBox_DrawFlowmapColors_StateChanged)
        self.Button_DisplayParameters.clicked.connect(self.display_parameters)

        self.Button_FlowmapExportFlowmaps.clicked.connect(self.save_current_flowmaps)
        self.Button_FlowmapGotoSaveLocation.clicked.connect(self.goto_flowmap_save_location)
        ##10. OpenGL Image

        # QOpenGLWidget erzeugen & den Designer-Container ersetzen
        self.OpenGL_MainImage : MyGL = MyGL(self.SCRLB_MainImage_Horizontal, self.SCRLB_MainImage_Vertical, self.SCRLB_MainImage_Zoom, self.doubleSpinBox_SCRLB_MainImage_Zoom, self.SCRLB_MainImage_OverallSpeed, self.doubleSpinBox_SCRLB_MainImage_OverallSpeed)
        layout = QVBoxLayout()
        layout.setContentsMargins(0,0,0,0)
        layout.addWidget(self.OpenGL_MainImage)
        self.RPLC_WDG_OpenGL_MainImage.setLayout(layout)
        QTimer.singleShot(0, self.setsavepropertiesandload)
        
        ##Widget Initializing
        QTimer.singleShot(0, self.init_scrollbars)
        QTimer.singleShot(0, self.init_managerprocess)
        self.show()

        #self.setsavepropertiesandload()   #QTimer fires BEFORE MyGL is initialized but it works??

    def init_managerprocess(self):        
        self.managerqueuein = mpmgr.Queue() 
        self.subprocesses = {}
        self.managerprocess = Process(target=ManagerProcess(self.managerqueuein, refreshrate = 10000).run)
        self.managerprocess.start()
        #self.threadupdatetimer = {}

    def managerprocess_start_process(self, functiontype : str, targetfunction, arguments):
        self.managerqueuein.put({"set_refreshrate" : 1})
        self.managerqueuein.put((functiontype, targetfunction, arguments))
        self.managerqueuein.put({"set_refreshrate" : 10000})

    def init_scrollbars(self):
        scrlbars = self.findChildren(QScrollBar)
        for scrlb in scrlbars:
            if hasattr(scrlb, "name") and "Alpha" in scrlb.name:
                scrlb.setValue(100)
                self.set_scrollbar_value_color(scrlb, 1)
                
    def setsavepropertiesandload(self):
        ##Save properties
        stt = ["SaveIndex", "SaveContent"]
        self.savetables =       {
                                self.table_SelectFiles      : [stt[0]],
                                self.table_SelectCluster    : [stt[0]],
                                #self.table_SelectLayer     : [stt[0]],
                                self.table_SelectNetwork    : [stt[0]],
                                self.table_SelectJunction   : [stt[0]],
                                self.table_SelectPath       : [stt[0]]
                                }   ##---> we generate the table contents from selected folder/file 
        self.savelineedits =    [
                                self.lineEdit_SelectFolder,
                                self.lineEdit_PanningTexture
                                ]
        self.savefilelocation = sys.argv[0].replace(re.search("\.[a-zA-Z]{1,4}$", sys.argv[0])[0], "_save.pkl")

        self.load_users_widgetinfos()
        ##End Save properties

    def select_folder(self):
        folder = select_folder_ui(initialdir=self.lineEdit_SelectFolder.text() if os.path.exists(self.lineEdit_SelectFolder.text()) else None)
        if folder:
            self.lineEdit_SelectFolder.setText(folder)
            self.update_SelectFiles()
    
    def update_SelectFiles(self, newrowselect = None):
        oldrowindex = self.table_SelectFiles.row(self.table_SelectFiles.currentItem())
        if os.path.exists(self.lineEdit_SelectFolder.text()):
            files = get_files_of_folder(self.lineEdit_SelectFolder.text(), allowedtypes=[".png", ".bmp", ".jpg", ".jpeg"])
            self.table_SelectFiles.setRowCount(len(files))
            for row, f in enumerate(files):
                fmgf = FlowMapGenFiles(f)
                item = QTableWidgetItem(f.name)
                item.setData(256, fmgf)              # 256 = Qt.UserRole
                self.table_SelectFiles.setItem(row, 0, item)
                #self.table_SelectFiles.setItem(row, 1, QTableWidgetItem(f.root))
        else:
            self.table_SelectFiles.setRowCount(0)
        if newrowselect is None:
            newrowselect = oldrowindex if oldrowindex else -1
        if newrowselect > -1 and self.table_SelectFiles.rowCount() -1 >= newrowselect: self.table_SelectFiles.setCurrentCell(newrowselect, 0)

    
    def get_curobjtypename(self, objtype : networkingtypes, cluster = None, network = None, junction = None, ppath = None):
        ind = networkingtypes.__args__.index(objtype)
        
        nms = []
        if ind > -1:
            nms.append(self.clusterobj)
        if ind > 0:
            cc = cluster if cluster else self.get_current_cluster() 
            nms.append(cc)
        if ind > 1:
            cc = network if network else self.get_current_network()
            nms.append(cc)
        if ind > 2:
            cc = junction if junction else self.get_current_junction()
            nms.append(cc)
        if ind == 4 or ind == 5:
            cc = ppath if ppath else self.get_current_path() 
            nms.append(cc)
        nms = [x.name for x in nms if not x is None]
        name = "_".join(nms)
        return name
    
    def file_selected(self):
        global file
        #print(f"file_selected")
        #has to unload old images
        if hasattr(self, "managerqueuein"): self.managerqueuein.put({"stop_workerprocesses" : ""})
        self.OpenGL_MainImage.clear()
        CurFlowMapGenFiles = self.get_current_flowmapgenfile()
        self.hadcluster = False

        if CurFlowMapGenFiles and os.path.exists(CurFlowMapGenFiles.BaseFile.fullname):
            file = CurFlowMapGenFiles.BaseFile
            img = self.OpenGL_MainImage.load_image_cv2(CurFlowMapGenFiles.BaseFile.fullname)
            if len(img.shape) == 3:
                h, w, d = img.shape
            else:
                h, w = img.shape
            self.OpenGL_MainImage.add_layer(ImageLayer, CurFlowMapGenFiles.BaseFile.fullname, "Base Image", 0, 1, False, color = (1,1,1))
            self.SCRLB_BaseImgAlpha.setValue(100)
            self.set_scrollbar_value_color(self.SCRLB_BaseImgAlpha)
            if os.path.exists(CurFlowMapGenFiles.Clusters.fullname):
                self.clusterobj : clusters = load_obj(CurFlowMapGenFiles.Clusters.fullname)
                self.display_clusters()
                self.hadcluster = True
        else:
            self.set_scrollbar_value_color(self.SCRLB_BaseImgAlpha, 1, (125,125,125), (125,125,125))
        if not self.hadcluster:
            if CurFlowMapGenFiles:
                self.clusterobj : clusters = clusters([], CurFlowMapGenFiles.BaseFile.name, CurFlowMapGenFiles.Clusters.fullname)
                self.display_clusters()       
            else:
                self.clusterobj : clusters = clusters([], "Cluster", "")
        self.update_clustermethod()
        self.save_users_widgetinfos()

    def baseimg_alpha_changed(self, val):
        if "Base Image" in self.OpenGL_MainImage.imagelayers:
            self.OpenGL_MainImage.layer_alpha_value_change(ImageLayer, "Base Image", val / 100)
            self.set_scrollbar_value_color(self.SCRLB_BaseImgAlpha)
        else:
            self.set_scrollbar_value_color(self.SCRLB_BaseImgAlpha, 0.5, (125,125,125), (125,125,125))
    
    def add_pointimage_to_layer(self, junction : junction, h, w, name, updateexisting = True):
        junction.img = np.zeros((h,w, 4), dtype=np.uint8)
        #print(f"add_pointimage_to_layer: junctiontype: ({type(junction)})")
        junction.img[junction.junctionpoint] = (125,125,255,255)
        global pointcolor
        self.OpenGL_MainImage.add_layer(layertype=PointLayer, displayobj=junction, layer_name=name, z_depth=4, alpha=1, selected=False, offset=0, speed=1, color=pointcolor["unselected"], updateexisting = updateexisting)

    def add_pointpath_to_layer(self, ppath, h, w, layername = "", updateexisting = True):
        global linecolor
        npath : pointpath = copy.deepcopy(ppath)                        
        npath.pts = np.array(npath.points, int)
        npath.img = np.zeros((h, w, 4), dtype=np.uint8); 
        npath.img[npath.pts[:,0], npath.pts[:,1]] = [255,255,125,255]
        for i in range(len(npath.points)):
            npath.points[i] = npath.points[i][::-1]
        npath.pts = npath.pts[:, [1, 0]]
        self.OpenGL_MainImage.add_layer(PathLayer, npath, layername, 3, 1, False, 0, 2, linecolor["unselected"], updateexisting)

    ###5. Cluster Start
    def display_clusters(self, updateexisting = True):
        #self.OpenGL_MainImage.doupdates = False
        Fmgf = self.get_current_flowmapgenfile()
        Fmgfname = Fmgf.FlowMapFile.name
        Fmgfformat = Fmgf.FlowMapFile.format
        Fmgfroot = Fmgf.FlowMapFile.root
        for cluster in self.clusterobj.cluster:
            h, w = cluster.clustermask.shape[0], cluster.clustermask.shape[1]
            for network in cluster.networks:
                #print(f"network:({network.layername})")
                for junction in network.network.keys(): #paths are arranged so that we always go forward!
                    #print(f"junction:({junction.layername})")
                    self.add_pointimage_to_layer(junction, h, w, junction.layername, updateexisting)
                    for ppath in junction.get_all_paths():
                        #print(f"jpaths:({ppath.layername})")
                        self.add_pointpath_to_layer(ppath, h, w, ppath.layername, updateexisting)
                        #print(f"added: ({a})")
                for ppath in network.singlepaths:
                    #print(f"spath:({ppath.layername})")
                    self.add_pointpath_to_layer(ppath, h, w, ppath.layername, updateexisting)
                if hasattr(network, "flowmapobjs"):
                    self.SCRLB_FlowmapAlpha.setValue(100)
                    for fmo in network.flowmapobjs:
                        self.add_flowmap_to_layer(fmo, h, w, fmo.name, updateexisting)
                else:
                    self.SCRLB_FlowmapAlpha.setValue(0)
                    self.set_scrollbar_value_color(self.SCRLB_FlowmapAlpha, 1, (125,125,125), (125,125,125))
        #self.OpenGL_MainImage.doupdates = True

    def update_clustermethod(self):
        #checks if there is any cluster image for the selected image using the selected method
        #if there is an cluster image, we take it until user wants to reload it because clustering takes time.. 
        CurFlowMapGenFiles : FlowMapGenFiles = self.get_current_flowmapgenfile()
        self.OpenGL_MainImage.doupdates = False
        if CurFlowMapGenFiles and os.path.exists(CurFlowMapGenFiles.ClusterFile.fullname):
            if self.hadcluster:                
                self.OpenGL_MainImage.remove_layer(ImageLayer, "Cluster_", True)
                for cluster in self.clusterobj.cluster:
                    newimg = np.full((cluster.clustermask.shape[0], cluster.clustermask.shape[1], 4), (-1,-1,-1,-1))
                    newimg[cluster.clustermask] = cluster.clusterid
                    self.OpenGL_MainImage.add_layer(ImageLayer, newimg, cluster.layername, 1, 0.5, False, 0, 1, (1,1,1))
            else:
                self.clusterobj : clusters = clusters([], "Cluster", CurFlowMapGenFiles.Clusters.fullname)
                self.clusterobj.rename_clusters_members_numeration()
                labels = self.OpenGL_MainImage.load_image_cv2(CurFlowMapGenFiles.ClusterFile.fullname)
                labels = labels.astype(np.int64)
                alpha = self.OpenGL_MainImage.load_image_cv2(CurFlowMapGenFiles.BaseFile.fullname)
                alpha = alpha[:,:,3].astype(bool)
                labels[~alpha, :] = -1
                #labels.swapaxes(0,1)
                uniques = np.unique(labels.reshape(-1,labels.shape[-1]), axis=0)
                self.OpenGL_MainImage.doupdates = False
                self.OpenGL_MainImage.remove_layer(ImageLayer, "Cluster_", True)
                for unique in uniques:
                    if unique[0] == -1: continue
                    mask = np.all(labels==unique, axis=-1)
                    newimg = np.zeros(labels.shape)
                    #if unique[0] == 0: unique = [255, 255, 255, 255]
                    newimg[mask] = unique
                    newimg[~mask] = [-1,-1,-1,0]
                    newcluster = self.clusterobj.add_cluster(mask, [], clusterid = unique, name = self.clusterobj.layername)
                    self.clusterobj.rename_clusters_members_numeration()
                    self.OpenGL_MainImage.add_layer(ImageLayer, newimg, newcluster.layername, 1, 0.5, False, 0, 1, (1,1,1))
                    
                self.clusterobj.save()
            val = 100            
        else:
            self.OpenGL_MainImage.doupdates = False
            self.OpenGL_MainImage.remove_layer(ImageLayer, "Cluster_", True)
            gclusters = [c for c in self.clusterobj.cluster]
            for cluster in gclusters:
                self.clusterobj.cluster.remove(cluster)
            val = 0
        self.OpenGL_MainImage.doupdates = True
        #if val != self.progressBar_ClusterMethod.value():
        self.update_clustertable()  #
        self.update_progressbar("Clustering",val)
        self.SCRLB_ClusterAlpha.setValue(val)
        #self.update_layertable()

    def cluster_method_reload(self):
        self.hadcluster = False
        CurFlowMapGenFiles : FlowMapGenFiles = self.get_current_flowmapgenfile()
        if CurFlowMapGenFiles and os.path.exists(CurFlowMapGenFiles.ClusterFile.fullname):
            os.remove(CurFlowMapGenFiles.ClusterFile.fullname)
        self.Button_ClusterMethodReload.setEnabled(False)
        self.update_progressbar("Clustering",25)
        self.update_clustermethod()
        self.start_process("Clustering", True)    
        
    def edit_cluster_method_parameters(self):
        CurClusterMethod = self.comboBox_ClusterMethod.currentText()
        Ecmp = ParametersEditUI(clustermethodparameters[CurClusterMethod])
        if Ecmp.exec():
            newparams = Ecmp.get_parameters()
            clustermethodparameters[CurClusterMethod] = newparams
    
    def get_new_index_from_old_new_and_tbl(self, oldrowindex : int, potentialnewrowindex : int, table : QTableWidget):
        if potentialnewrowindex is None:
            if oldrowindex:
                potentialnewrowindex = oldrowindex
            else:
                if table.rowCount() > 0:
                    potentialnewrowindex = 0
                else:
                    potentialnewrowindex = -1
        if potentialnewrowindex > -1 and table.rowCount() -1 >= potentialnewrowindex:
            return potentialnewrowindex
        #elif table.rowCount() > 0:
        #    return
        return None

    def update_clustertable(self, newrowselect = None):
        oldrowindex = self.table_SelectCluster.row(self.table_SelectCluster.currentItem())
        if self.table_SelectCluster.rowCount() != len(self.clusterobj.cluster):
                self.table_SelectCluster.setRowCount(len(self.clusterobj.cluster))
        
        if len(self.clusterobj.cluster) != 0:
            for row, cluster in enumerate(self.clusterobj.cluster):
                #fmgf = FlowMapGenFiles(f)
                layer = self.OpenGL_MainImage.imagelayers[cluster.name]
                clusterstr = layer.name
                if self.table_SelectCluster.item(row, 0) and self.table_SelectCluster.item(row, 0).text() == clusterstr:
                    nameitem = self.get_table_item(self.table_SelectCluster, clusterstr)[1]
                else:
                    nameitem = QTableWidgetItem()
                    nameitem.setFlags(nameitem.flags() & ~Qt.ItemIsEditable)
                    self.table_SelectCluster.setItem(row, 0, nameitem)
                nameitem.setText(clusterstr)
                nameitem.setData(256, (layer, cluster))

        newrowselect = self.get_new_index_from_old_new_and_tbl(oldrowindex, newrowselect, self.table_SelectCluster)
        if newrowselect: 
            reselected = self.table_SelectCluster.currentRow() == newrowselect
            self.table_SelectCluster.setCurrentCell(newrowselect, 0)
            if reselected:
                self.cluster_selected()
        else:
            self.update_networktable()

    def cluster_selected(self):
        #print(f"cluster_selected")
        curclust = self.get_current_cluster()
        if curclust: 
            self.OpenGL_MainImage.single_layer_selection(curclust.layername, ImageLayer)
            self.update_networktable()
            self.save_users_widgetinfos()
        
            
    def cluster_alpha_changed(self, val):
        hascluster = False
        for x in self.OpenGL_MainImage.imagelayers.values():
            if x.name.startswith("Cluster_"):
                hascluster = True
                break
        if hascluster:
            self.OpenGL_MainImage.layer_alpha_value_change(ImageLayer, "Cluster_", val / 100.0, True)
            self.set_scrollbar_value_color(self.SCRLB_ClusterAlpha)
        else:
            self.set_scrollbar_value_color(self.SCRLB_ClusterAlpha, 1, (125,125,125), (125,125,125))
    ###4.Cluster End
    
    ##5. Networks Start
    def network_selected(self):
        global linecolor
        curnet = self.get_current_network()
        #print(f"network_selected")
        if curnet:
            self.OpenGL_MainImage.change_layer_color(curnet.layername, PathLayer, newcolor=linecolor["halfselected"], deselectcolor=linecolor["unselected"], changemultiple=True, deselectothers=True)
        self.update_junctiontable()
        self.save_users_widgetinfos()
        

    def update_networktable(self, newrowselect = None):
        oldrowindex = self.table_SelectNetwork.row(self.table_SelectNetwork.currentItem())
        curclust : cluster = self.get_current_cluster()
        if not curclust:
            self.table_SelectNetwork.setRowCount(0)
            self.update_junctiontable()
            return
        
        if self.table_SelectNetwork.rowCount() != len(curclust.networks):
            self.table_SelectNetwork.setRowCount(len(curclust.networks))

        if len(curclust.networks) != 0:
            for row, network in enumerate(curclust.networks):
                #fmgf = FlowMapGenFiles(f)
                #layer = self.OpenGL_MainImage.[network.name]
                networkstr = network.name
                if self.table_SelectNetwork.item(row, 0) and self.table_SelectNetwork.item(row, 0).text() == networkstr:
                    nameitem = self.get_table_item(self.table_SelectNetwork, networkstr)[1]
                else:
                    nameitem = QTableWidgetItem()
                    nameitem.setFlags(nameitem.flags() & ~Qt.ItemIsEditable)
                    self.table_SelectNetwork.setItem(row, 0, nameitem)
                nameitem.setText(networkstr)
                nameitem.setData(256, network)
        newrowselect = self.get_new_index_from_old_new_and_tbl(oldrowindex, newrowselect, self.table_SelectNetwork)
        if newrowselect:
            reselected = self.table_SelectNetwork.currentRow() == newrowselect
            self.table_SelectNetwork.setCurrentCell(newrowselect, 0)
            if reselected:
                self.network_selected()
        else:
            curnet = self.get_current_network()
            if curnet:
                nm = curnet.layername
            else:
                nm = "42gm§TNj§N%JN%kjik3NK§Nnj::___??"
            global linecolor
            self.OpenGL_MainImage.change_layer_color(nm, PathLayer, newcolor=linecolor["halfselected"], deselectcolor=linecolor["unselected"], changemultiple=True, deselectothers=True)
            self.update_junctiontable()

    def network_generate_all(self):
        CurFlowMapGenFiles : FlowMapGenFiles = self.get_current_flowmapgenfile()
        if CurFlowMapGenFiles and self.table_SelectCluster.rowCount() != 0:
            for c in self.clusterobj.cluster:
                c.networks = []
            self.OpenGL_MainImage.remove_layer(PathLayer, "", True)
            self.OpenGL_MainImage.remove_layer(PointLayer, "", True)
            self.Button_NetworkGenerateAll.setEnabled(False)
            self.Button_NetworkGenerateParameters.setEnabled(False)
            #self.Button_NetworkGenerate.setEnabled(False)
            #self.Button_NetworkSplitParameters.setEnabled(False)
            self.update_progressbar("NetworkGeneration",1)
            self.start_process("NetworkGeneration", True)

    def network_generate_parameters(self):
        pass
    
    def network_split(self):
        pass

    def network_split_parameters(self):
        pass

    ##5. Networks End

    ##6. Junctions Start
    def junction_alpha_changed(self, val):
        self.OpenGL_MainImage.layer_alpha_value_change(PointLayer, "", val / 100, change_multiple = True)
        self.set_scrollbar_value_color(self.SCRLB_JunctionAlpha, 1)

    def junction_selected_doubleclick(self):
        curjunc = self.get_current_junction()
        if curjunc:
            donepaths = set()
            for ppath in curjunc.get_all_paths():
                if not ppath in donepaths:
                    ppath.flip()
                    for cluster in self.clusterobj.cluster:
                        h, w = cluster.clustermask.shape[0], cluster.clustermask.shape[1]
                        break
                    self.clusterobj.save()
                    sel = self.OpenGL_MainImage.get_layercollection_by_type(PathLayer)[ppath.layername].selected
                    self.add_pointpath_to_layer(ppath, h, w, ppath.layername, True)
                    self.OpenGL_MainImage.get_layercollection_by_type(PathLayer)[ppath.layername].selected = sel

    def junction_selected(self):
        #print(f"junction_selected")
        curjunc = self.get_current_junction()
        if curjunc:
            curname = curjunc.layername
            global pointcolor
            self.OpenGL_MainImage.change_layer_color(curname, PointLayer, pointcolor["selected"], pointcolor["unselected"], True, True)
            self.OpenGL_MainImage.single_layer_selection(curname, PointLayer, True)
        self.update_pathtable(None)
        self.save_users_widgetinfos()
        

    def update_junctiontable(self, newrowselect = None):
        oldrowindex = self.table_SelectJunction.row(self.table_SelectJunction.currentItem())
        curnetwork : network = self.get_current_network()
        if not curnetwork:
            self.table_SelectJunction.setRowCount(0)
            return
        if self.table_SelectJunction.rowCount() != len(curnetwork.network):
            self.table_SelectJunction.setRowCount(len(curnetwork.network))
        curjuncs = curnetwork.network.keys()
        if len(curjuncs) != 0:
            for row, junc in enumerate(curjuncs):
                juncstr = junc.name
                if self.table_SelectJunction.item(row, 0) and self.table_SelectJunction.item(row, 0).text() == juncstr:
                    nameitem = self.get_table_item(self.table_SelectJunction, juncstr)[1]
                else:
                    nameitem = QTableWidgetItem()
                    nameitem.setFlags(nameitem.flags() & ~Qt.ItemIsEditable)
                    self.table_SelectJunction.setItem(row, 0, nameitem)
                nameitem.setText(juncstr)
                nameitem.setData(256, junc)
        newrowselect = self.get_new_index_from_old_new_and_tbl(oldrowindex, newrowselect, self.table_SelectJunction)
        if newrowselect: 
            reselected = self.table_SelectJunction.currentRow() == newrowselect
            self.table_SelectJunction.setCurrentCell(newrowselect, 0)
            if reselected:
                self.junction_selected()
        else:
            self.update_pathtable(None)

    ##6. Junctions End

    ##7. Paths Start
    def path_selected(self):
        #print(f"path_selected")
        curnet = self.get_current_network()
        global linecolor
        if curnet:
            self.OpenGL_MainImage.change_layer_color(curnet.layername, PathLayer, linecolor["halfselected"], linecolor["unselected"])
        else:
            self.OpenGL_MainImage.change_layer_color("n3rj21j bJ§J3rmk'§-§55((;;%))", PathLayer, linecolor["halfselected"], linecolor["unselected"])
        curpath = self.get_current_path()
        if curpath:
            #we first change all colors of the network to unselect the last selection            
            #then we reselect new selection
            self.OpenGL_MainImage.change_layer_color(curpath.layername, PathLayer, linecolor["selected"], linecolor["unselected"], False, False)
            self.OpenGL_MainImage.single_layer_selection(curpath.layername, PathLayer, True)
        
        self.save_users_widgetinfos()
        
    def path_selected_doubleclick(self):
        curpath = self.get_current_path()
        if curpath:
            curpath.flip()
            for cluster in self.clusterobj.cluster:
                h, w = cluster.clustermask.shape[0], cluster.clustermask.shape[1]
                break
            self.clusterobj.save()
            self.add_pointpath_to_layer(curpath, h, w, curpath.layername, True)
            self.OpenGL_MainImage.set_layer_as_selected(PathLayer, curpath.layername)

    def path_alpha_changed(self, val):
        self.OpenGL_MainImage.layer_alpha_value_change(PathLayer, "", val / 100, change_multiple = True)
        self.set_scrollbar_value_color(self.SCRLB_PathAlpha, 1)

    def path_delete(self):
        curpath = self.get_current_path()
        if curpath:
            if curpath.layername in self.OpenGL_MainImage.pathlayers:
                del self.OpenGL_MainImage.pathlayers[curpath.layername]
            curpath.remove_pointpath()
            self.clusterobj.save()
            self.update_pathtable()

    def update_pathtable(self, newrowselect = None):
        #print(f"update_pathtable called")
        oldrowindex = self.table_SelectPath.row(self.table_SelectPath.currentItem())
        curjunction : junction = self.get_current_junction()
        curnetwork : network = self.get_current_network()
        
        if not curjunction and not curnetwork:
            curpath = self.get_current_path()
            if curpath.layername in self.OpenGL_MainImage.pathlayers:
                self.OpenGL_MainImage.pathlayers[curpath.layername].selected = False
            self.table_SelectPath.setRowCount(0)
            #print(f"return after setrowcount 0")
            return
        pathdic = {}
        if curjunction:
            #print(f"curjunction name: {curjunction.layername}")
            pathdic = curjunction.get_all_paths()
            pathdic = {"junctionpath" : pathdic, "singlepath" : curnetwork.singlepaths}
        else:
            pathdic = {"singlepath" : curnetwork.singlepaths}
        pathcount = 0
        for val in pathdic.values():
            for v in val:
                pathcount += 1
        #print(f"pathcount = {pathcount}")
        if self.table_SelectPath.rowCount() != pathcount:
            self.table_SelectPath.setRowCount(pathcount)
            #print(f"setpath row count to {pathcount}")
        if pathcount != 0:
            for pathsource, paths in pathdic.items():
                for row, path in enumerate(paths):
                    #fmgf = FlowMapGenFiles(f)
                    #layer = self.OpenGL_MainImage.[network.name]
                    pathstr = path.name
                    if self.table_SelectPath.item(row, 0) and self.table_SelectPath.item(row, 0).text() == pathstr:
                        nameitem = self.get_table_item(self.table_SelectPath, pathstr)[1]
                        sourceitem = self.get_table_item(self.table_SelectPath, pathstr, 1)[1]
                        sourceitem.setText(pathsource)
                    else:
                        nameitem = QTableWidgetItem()
                        nameitem.setFlags(nameitem.flags() & ~Qt.ItemIsEditable)
                        self.table_SelectPath.setItem(row, 0, nameitem)
                        sourceitem = QTableWidgetItem(pathsource)
                        self.table_SelectPath.setItem(row, 1, sourceitem)
                    nameitem.setText(pathstr)
                    nameitem.setData(256, path)
        newrowselect = self.get_new_index_from_old_new_and_tbl(oldrowindex, newrowselect, self.table_SelectPath)
        if newrowselect: 
            reselected = self.table_SelectPath.currentRow() == newrowselect
            self.table_SelectPath.setCurrentCell(newrowselect, 0)
            if reselected:
                self.path_selected()
        else:
            curpath = self.get_current_path()
            if curpath:
                #we first change all colors of the network to unselect the last selection
                global linecolor
                self.OpenGL_MainImage.change_layer_color(curnetwork.layername, PathLayer, linecolor["halfselected"], linecolor["unselected"])
                #then we reselect new selection
                self.OpenGL_MainImage.change_layer_color(curpath.layername, PathLayer, linecolor["selected"], linecolor["unselected"], False, False)
        
    ##7. Paths End
    
    ##8. Flowmap Start
    def flowmap_selected(self):
        pass
    def update_flowmap_table(self):
        oldrowindex = self.table_SelectPath.row(self.table_SelectPath.currentItem())

    def flowmap_alpha_changed(self, val):
        self.OpenGL_MainImage.layer_alpha_value_change(FlowmapLayer, "", val / 100, change_multiple = True)
        self.set_scrollbar_value_color(self.SCRLB_FlowmapAlpha, 1)

    def panning_x_changed(self, val):
        self.OpenGL_MainImage.set_panner_u(val)

    def panning_y_changed(self, val):
        self.OpenGL_MainImage.set_panner_v(val)

    def checkBox_DrawFlowmapColors_StateChanged(self, val):
        checked = self.checkBox_DrawFlowmapColors.isChecked()
        for fl in self.OpenGL_MainImage.flowmaplayers.values():
            fl.drawAsColor = int(checked)

    def display_parameters(self):
        global linecolor, pointcolor
        params = {"Flowmap Color Channel X" : self.OpenGL_MainImage.ColorChannelX,
                    "Flowmap Color Channel Y" : self.OpenGL_MainImage.ColorChannelY,
                    "linecolor" : linecolor,
                    "pointcolor" : pointcolor}
        
        pmeui = ParametersEditUI(params)
        if pmeui.exec():
            newparams = pmeui.get_parameters()
            self.OpenGL_MainImage.ColorChannelX = newparams["Flowmap Color Channel X"]
            self.OpenGL_MainImage.ColorChannelY = newparams["Flowmap Color Channel Y"]

            xlinecolor = newparams["linecolor"]
            player : PointLayer
            for player in self.OpenGL_MainImage.pathlayers.values():
                for colname, pcol in linecolor.items():
                    if player.color == pcol:
                        player.color = xlinecolor[colname]
            xpointcolor = newparams["pointcolor"]
            for player in self.OpenGL_MainImage.pointlayers.values():
                for colname, pcol in pointcolor.items():
                    if player.color == pcol:
                        player.color = xpointcolor[colname]
            linecolor, pointcolor = (xlinecolor, xpointcolor)

    def select_panningtexture(self):
        potentialoldfolder = os.path.dirname(self.lineEdit_PanningTexture.text())
        file = select_file_ui(initialdir=potentialoldfolder if os.path.exists(potentialoldfolder) else None,
                              filetypes=[("Bilder", ("*.png","*.jpg","*.jpeg","*.bmp"))])
        if file and os.path.exists(file):
            self.lineEdit_PanningTexture.setText(file)

    def add_flowmap_to_layer(self, nflowmap : flowmapobj, h, w, layername = "", updateexisting = True):
        self.OpenGL_MainImage.add_layer(layertype=FlowmapLayer, displayobj=nflowmap, layer_name=layername, z_depth=3, alpha=self.SCRLB_FlowmapAlpha.value() / 100, selected=False, offset=0, speed=1, color=(1,1,1), updateexisting=updateexisting)
        self.OpenGL_MainImage.flowmaplayers[layername].drawAsColor = int(self.checkBox_DrawFlowmapColors.isChecked())
        
    def flowmap_generate_all(self):
        self.update_progressbar("FlowmappingAll", 0.1)
        self.start_process("FlowmappingAll", True)
        
    def flowmap_generate_selected_network(self):
        curnet = self.get_current_network()
        if curnet:
            self.update_progressbar("FlowmappingSingle", 0.1)
            self.start_process("FlowmappingSingle", True)

    def clear_flowmaps(self):
        for cluster in self.clusterobj.cluster:
            for network in cluster.networks:
                network.flowmapobjs = []
        self.OpenGL_MainImage.remove_layer(FlowmapLayer, "", True)

    def save_current_flowmaps(self, clusterfile):
        Fmgf = clusterfile
        if not clusterfile: Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
        for c in self.clusterobj.cluster:
            for net in c.networks:
                for flowmap in net.flowmapobjs:
                    self.save_flowmap(clusterfile=clusterfile, flowmap=flowmap)   
    

    def save_flowmap(self, clusterfile, flowmap):
        Fmgf = clusterfile
        if not clusterfile: Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
            
        if Fmgf and flowmap:
            SaveFlowmap(Fmgf.FlowMapFile.root,
                flowmap.name + Fmgf.FlowMapFile.format,
                Fmgf.FlowMapFile.format,
                flowmap.flowmap_image, "")
            return True
        return False

    def goto_flowmap_save_location(self, clusterfile):
        Fmgf = clusterfile
        if not clusterfile: Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
        if Fmgf:
            subprocess.Popen(r'explorer /open,"' + Fmgf.FlowMapFile.root.replace(r'/', '\\'[0])+ '"')
    ##8. Flowmap End

    
    ###Multithread Start
    def start_process(self, ProcessType : processtypes, killoldprocess = True):            
        UpdateQueue = mpmgr.Queue() 
        TerminateQueue = mpmgr.Queue() 
        UpdateTimer = QTimer()
        #TerminateTimer = QTimer()
        
        fmgf = copy.copy(self.get_current_flowmapgenfile())
        path = fmgf.BaseFile.fullname
        ogfile = fmgf.BaseFile
        match ProcessType:
            case "Clustering":
                targetfunction = cluster_method_reload_run
                UpdateTimer.LambdaFunction = partial(
                                                    self.check_thread_progress,
                                                    ProcessType=ProcessType,
                                                    queue=UpdateQueue,
                                                    timer=UpdateTimer
                                                )
                UpdateTimer.timeout.connect(UpdateTimer.LambdaFunction)
                method = self.comboBox_ClusterMethod.currentText()
                arguments = [UpdateQueue, TerminateQueue, path, ogfile, method, clustermethodparameters]
            case "NetworkGeneration":
                targetfunction = network_generate_run
                UpdateTimer.LambdaFunction = partial(
                                                    self.check_thread_progress,
                                                    ProcessType=ProcessType,
                                                    queue=UpdateQueue,
                                                    timer=UpdateTimer
                                                )
                UpdateTimer.timeout.connect(UpdateTimer.LambdaFunction)
                #tblit = collect(self.clusterobj)
                tblit = copy.copy(self.clusterobj)
                #clustermask = copy.deepcopy(tblit.clustermask)  #-> at this point tblit or better its clustermask is the whole map! -> return will be all networks. they get split in the next step
                arguments = [UpdateQueue, TerminateQueue, path, ogfile, tblit]
            case "NetworkSplitting":
                targetfunction = network_split_run
                UpdateTimer.LambdaFunction = partial(
                                                    self.check_thread_progress,
                                                    ProcessType=ProcessType,
                                                    queue=UpdateQueue,
                                                    timer=UpdateTimer
                                                )
                UpdateTimer.timeout.connect(UpdateTimer.LambdaFunction)
                tblit : clusters = copy.copy(self.clusterobj)
                arguments = [UpdateQueue, TerminateQueue, tblit, ogfile, path]
            case "Pathing":
                pass
            case "Junctioning":
                pass
            case "FlowmappingAll":
                self.clear_flowmaps()
                targetfunction = flowmap_generate_all_run
                UpdateTimer.LambdaFunction = partial(
                                                self.check_thread_progress,
                                                ProcessType=ProcessType,
                                                queue=UpdateQueue,
                                                timer=UpdateTimer
                                            )
                UpdateTimer.timeout.connect(UpdateTimer.LambdaFunction)
                curclusters = copy.copy((fmgf, self.clusterobj))
                arguments = [UpdateQueue, TerminateQueue, curclusters, ogfile, path]
            case "FlowmappingSingle":
                curnet = self.get_current_network()
                curnet.flowmapobjs = []
                self.OpenGL_MainImage.remove_layer(FlowmapLayer, curnet.layername, True)
                targetfunction = flowmap_generate_single_run
                UpdateTimer.LambdaFunction = partial(
                                                    self.check_thread_progress,
                                                    ProcessType=ProcessType,
                                                    queue=UpdateQueue,
                                                    timer=UpdateTimer
                                                )
                UpdateTimer.timeout.connect(UpdateTimer.LambdaFunction)
                curclusters = copy.copy((fmgf, [curnet]))
                arguments = [UpdateQueue, TerminateQueue, curclusters, ogfile, path]
        # Shared Memory anlegen ->nix zum sharen
        #shm = shared_memory.SharedMemory(create=True, size=arr.nbytes)
        #shm.buf[:arr.nbytes] = arr.tobytes()
        
        # Start Process
        ptype = copy.copy(ProcessType)
        #self.threadupdatetimer[ptype] = UpdateTimer
        self.managerprocess_start_process(ptype, targetfunction, arguments)
        #self.managerprocess.UpdateQueue.put((ptype, targetfunction, arguments, UpdateTimer))#, TerminateTimer)
        #self.parallelprocesses[ProcessType] = BetterProcess(Process(
        #    target=targetfunction,
        #    args=tuple(arguments)
        #), UpdateQueue, UpdateTimer, TerminateQueue, TerminateTimer)        
        
        #self.parallelprocesses[ProcessType].start()
        UpdateTimer.start(100)
        #TerminateTimer.start(100)
        #self.shm = shm  # behalten, um später freizugeben

    def check_thread_progress(self, ProcessType : processtypes, queue, timer):
        if self.checkingprogress: return
        self.checkingprogress = True
        if queue.empty():
            if ProcessType == "Clustering":
                self.joke_update_progressbar(ProcessType)
            self.checkingprogress = False
            return
        
        while not queue.empty():            
            val = queue.get()
            #print(f"PT: ({ProcessType}) got val ({val}))")
            if type(val) == int or type(val) == float:
                if val == 100:
                    self.stop_timer(timer)
                else:
                    self.update_progressbar(ProcessType, val)
            elif not isinstance(val, Exception): #we give back keyword dictionary
                try:
                    self.process_queuetrigger(ProcessType, val, timer)
                except Exception as e:
                    print(f"Error in process_queuetrigger: ({e})")
            else:
                print(f"Error: ({val}), type ({type(val)})")
                #self.threadupdatetimer[ProcessType] == None
        self.checkingprogress = False

    def process_queuetrigger(self, ProcessType : processtypes, val, timer):
        #self.stop_workerprocess(ProcessType)
        match ProcessType:
            case "Clustering":                
                if type(val) == tuple:
                    path, labels, clustered, alpha = val
                    Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
                    SaveFlowmap(Fmgf.ClusterFile.root,
                                Fmgf.ClusterFile.name,
                                Fmgf.ClusterFile.format,
                                labels, "")
                    self.hadcluster = False
                    self.update_clustermethod()                    
                    self.Button_ClusterMethodReload.setEnabled(True)
                    QTimer.singleShot(0, partial(self.stop_timer,timer))
                return
            
            case "NetworkGeneration":
                if type(val) == tuple:
                    if len(val) == 3:
                        #self.update_progressbar("NetworkGeneration", 100)
                        path, newnet, i = val
                        #newnet = resolve_reg(newnet)
                        self.clusterobj.cluster[i].networks = [newnet]
                elif type(val) == clusters:
                    self.clusterobj : clusters = val
                elif val == "End":                    
                    self.update_progressbar("NetworkGeneration",100)
                    self.update_clustertable()
                    self.clusterobj.rename_clusters_members_numeration(self.clusterobj)
                    self.display_clusters(True)                    
                    self.clusterobj.save()
                    self.Button_NetworkGenerateAll.setEnabled(True)
                    self.Button_NetworkGenerateParameters.setEnabled(True)
                    QTimer.singleShot(0, partial(self.stop_timer,timer))
                    #self.Button_NetworkSplit.setEnabled(True)
                    #self.Button_NetworkSplitParameters.setEnabled(True)

                    #self.update_networktable(0)
                    #self.stop_timer(timer)
                    #self.start_process("NetworkSplitting", True)
                else:
                    self.update_progressbar("NetworkGeneration",0)
                    print("Exception occured while trying to generate networks: ", val)
                    

            case "NetworkSplitting":
                if type(val) == tuple:
                    pass
                elif val == "End":
                    pass
                else:
                    print(f"Error while NetworkSplitting: ", val)
                    self.update_progressbar("NetworkGeneration",0)
                
                self.Button_NetworkGenerateAll.setEnabled(True)
                self.Button_NetworkGenerateParameters.setEnabled(True)
                #self.Button_NetworkSplit.setEnabled(True)
                #self.Button_NetworkSplitParameters.setEnabled(True)

            case "FlowmappingAll":
                if type(val) == flowmapobj:
                    flowmap : flowmapobj = val
                    #flowmap : flowmapobj = resolve_reg(val)fmoname = "_".join([cluster.name, network.name, "junctions"])
                    h,w,d = flowmap.flowmap_image.shape
                    Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
                    SaveFlowmap(Fmgf.FlowMapFile.root,
                                flowmap.name + Fmgf.FlowMapFile.format,
                                Fmgf.FlowMapFile.format,
                                flowmap.flowmap_image, "")
                    
                    self.add_flowmap_to_layer(flowmap, h, w, flowmap.name)

                    curnet = self.get_network(flowmap.name.replace("_singlepaths", "").replace("_junctions", ""))
                    if curnet:
                        if not hasattr(curnet, "flowmapobjs"):
                            curnet.flowmapobjs = []
                        curnet.flowmapobjs.append(flowmap)
                        self.clusterobj.save()
                elif val == "End":
                    QTimer.singleShot(0, partial(self.stop_timer,timer))
                    print(f"End of Flowmap generation")

            case "FlowmappingSingle":
                if type(val) == flowmapobj:
                    flowmap : flowmapobj = val
                    #flowmap : flowmapobj = resolve_reg(val)fmoname = "_".join([cluster.name, network.name, "junctions"])
                    h,w,d = flowmap.flowmap_image.shape
                    Fmgf : FlowMapGenFiles = self.get_current_flowmapgenfile()
                    SaveFlowmap(Fmgf.FlowMapFile.root,
                                flowmap.name + Fmgf.FlowMapFile.format,
                                Fmgf.FlowMapFile.format,
                                flowmap.flowmap_image, "")
                    
                    self.add_flowmap_to_layer(flowmap, h, w, flowmap.name)

                    curnet = self.get_network(flowmap.name.replace("_singlepaths", "").replace("_junctions", ""))
                    if curnet:
                        if not hasattr(curnet, "flowmapobjs"):
                            curnet.flowmapobjs = []
                        curnet.flowmapobjs.append(flowmap)
                        self.clusterobj.save()
                elif val == "End":
                    QTimer.singleShot(0, partial(self.stop_timer,timer))
                    print(f"End of Flowmap generation")

    def stop_timer(self, timer: Queue):
        if timer:            
            if hasattr(timer, "LambdaFunction"):
                try:
                    timer.timeout.disconnect(timer.LambdaFunction)
                except:
                    pass
            try:
                timer.stop()
                timer.deleteLater()
            except:
                pass
    ###Multithread End
    
    def get_lerp_color(self, color0 = (0,255,0), color1 = (255,165,0), alpha = 0.0):
        outcol = []
        for i in range(len(color0)):
            outcol.append(max(0,min(255, int(color0[i] + alpha * (color1[i]-color0[i])))))
        return outcol
    
    def get_relative_progress(self, minimum : float | int, optimum : float | int, maximum : float | int, current : float | int):
        if current > optimum:
            if maximum != optimum: 
                ratio = 1 - (maximum - current) / (maximum - optimum)
            else:
                ratio = 1 - (maximum - current) / (maximum + 0.0001 - optimum)
        else:
            if optimum != minimum:
                ratio = (optimum - current) / (optimum - minimum)
            else:
                ratio = (optimum - current) / (optimum + 0.0001 - minimum)
        return ratio
    
    def get_background_color_Qt_string(self, color = (0,255,0)):
        outstr = f"background-color: rgb("
        for i, col in enumerate(color):
            if i != 0:
                outstr += ", " + str(col)
            else:
                outstr += str(col)
        outstr += ");"
        return outstr
    
    def set_scrollbar_value_color(self, scrollbar, optimum : float = 1.0, basergb = (0, 255, 0), targetrgb = (255, 165, 0)):
        scv = scrollbar.value() / 100
        scmax = scrollbar.maximum() / 100
        scmin = scrollbar.minimum() / 100
        ratio = self.get_relative_progress(scmin, optimum, scmax, scv)
        color = self.get_background_color_Qt_string(self.get_lerp_color(basergb, targetrgb, alpha = ratio))
        scrollbar.setStyleSheet(color)

    def joke_update_progressbar(self, ProcessType : processtypes):
        self.update_progressbar(ProcessType, 1, True)
    
    def update_progressbar(self, ProcessType : processtypes, value : int | float, isjoke = False):
        match ProcessType:
            case "Clustering":
                Pb = self.progressBar_ClusterMethod
            case "NetworkGeneration":
                Pb = self.progressBar_Network
            case "NetworkSplitting":
                Pb = self.progressBar_Network
            case "Junctioning": #-> are part of networking and have no individual bar
                return
                #Pb = self.prgre    -
            case "Pathing":
                return
                #Pb = self.progressBar_PathMethod
            case "FlowmappingAll":
                Pb = self.progressBar_FlowmapGenerate
            case "FlowmappingSingle":
                Pb = self.progressBar_FlowmapGenerate
        if isjoke:
            value = min(99, max(0, Pb.value() + (random() - 0.5 )*10))
            
        colorstr = self.get_background_color_Qt_string(self.get_lerp_color((255,0,0),(0,255,0), value/100))[:-1]

        xstr = """
                            QProgressBar {
                                border: 2px solid grey;
                                border-radius: 5px;
                                text-align: center;
                            }
                            QProgressBar::chunk {
                                """ + colorstr + """;
                                width: 20px;
                            }"""
        if value != 100:
            Pb.setStyleSheet(xstr)
        elif value == 100 and Pb.value != 100:
            Pb.setStyleSheet(xstr)
        if not ProcessType == "FlowmappingAll" and not ProcessType == "FlowmappingSingle":
            Pb.setValue(value)
        else:
            Pb.setValue(value * 100)
            if value != 100:
                self.progressBar_FlowmapGenerate.setFormat("%.02f %%" % value)
            else:
                self.progressBar_FlowmapGenerate.setFormat("100 %")

    def get_table_item_data(self, table: QTableWidget, name: Optional[str] = None, column : int = 0):
        row, item = self.get_table_item(table, name, column)
        if item:
            return item.data(256)
        return None
    
    def get_table_item(self, table: QTableWidget, name: Optional[str] = None, column : int = 0) -> QTableWidgetItem | None:
        if not name:
            return table.currentRow(), table.item(table.currentRow(), column)
        for row in range(table.rowCount()):
            item = table.item(row, 0)  # erste Spalte
            if item and item.text() == name:
                return row, table.item(row, column)
        return -1, None
    
    def get_current_flowmapgenfile(self) -> FlowMapGenFiles | None : return self.get_table_item_data(self.table_SelectFiles)

    def isanumber(self, numstr):
        try:
            a = int(numstr)
        except:
            try:
                a = float(numstr)                
            except:
                return False
        return True
    
    def get_type_name_dict_from_namechain(self, namechain):
        nms = namechain.split("_")
        nmdict = {}
        lytype = None
        for nm in nms:
            if self.isanumber(nm):
                nmdict[lytype] += "_" + nm
            if nm == "Clusters":
                lytype = clusters
            elif nm == "Cluster":
                lytype = cluster
            elif nm == "Network":
                lytype = network
            elif nm == "Junction":
                lytype = junction
            elif nm == "JunctionPath":
                lytype = pointpath
            elif nm == "SinglePath":
                lytype = pointpath
            nmdict[lytype] = nm
        return nmdict
    
    def get_current_cluster(self) -> cluster | None: 
        curcluster = self.get_table_item_data(self.table_SelectCluster)
        if curcluster:
            curcluster = curcluster[1]
        return curcluster    
    
    def get_cluster(self, name : str) -> cluster | None: 
        for cluster in self.clusterobj:
            if cluster.name == name:
                return cluster
        return None

    
    def get_current_network(self) -> network | None: return self.get_table_item_data(self.table_SelectNetwork)    
    
    def get_network(self, name : str, ccluster : Optional[cluster] = None, ExactMatch = True) -> network | None:
        if ccluster:
            Clusters = cwrap()
            Clusters.cluster = [ccluster]
        else:
            Clusters = self.clusterobj

        if Clusters:
            for c in Clusters.cluster:
                for n in c.networks:
                    if (ExactMatch and n.layername == name) or (not ExactMatch and name in n.layername):
                        return n
        return None

    
    def get_current_junction(self) -> junction | None: return self.get_table_item_data(self.table_SelectJunction)    
    
    def get_junction(self, name : str, nnetwork : Optional[network] = None, ExactMatch = True) -> junction | None:
        if nnetwork:
            Clusters = cwrap()
            Clusters.cluster = [cwrap()]
            Clusters.cluster[0].networks = [nnetwork]
        else:
            Clusters = self.clusterobj
        if Clusters:
            for c in Clusters.cluster:
                for n in c.networks:
                    for j, none in n.network.items():
                        if (ExactMatch and j.layername == name) or (not ExactMatch and name in j.layername):
                            return j
        return None

    
    def get_current_path(self) -> pointpath | None: return self.get_table_item_data(self.table_SelectPath)
    
    def get_path(self, name : str, nnetwork : Optional[network] = None, ExactMatch = True) -> pointpath | None:        
        if nnetwork:
            Clusters = cwrap()
            Clusters.cluster = [cwrap()]
            Clusters.cluster[0].networks = [nnetwork]
        else:
            Clusters = self.clusterobj
            
        if Clusters:
            for c in Clusters.cluster:
                for n in c.networks:
                    for pp in n.singlepaths:
                        if (ExactMatch and pp.layername == name) or (not ExactMatch and name in pp.layername):
                            return pp
                    for j in n.junctions:
                        for pp in j.get_all_paths():
                            if (ExactMatch and pp.layername == name) or (not ExactMatch and name in pp.layername):
                                return pp
        return None

    def save_table(self, table: QTableWidget):
        data = []
        SaveIndexes = "SaveIndex" in self.savetables[table]
        SaveContent = "SaveContent" in self.savetables[table]
        if SaveContent:
            for row in range(table.rowCount()):
                row_data = []
                for col in range(table.columnCount()):
                    item = table.item(row, col)
                    if item is not None:
                        row_data.append({
                            "text": item.text(),
                            "user_data": item.data(256)  # dein Objekt
                        })
                    else:
                        row_data.append(None)
                data.append(row_data)
        return {
                    "object_name": table.objectName(),  # eindeutiger Name
                    "data": data,
                    "lastselectedindexes": [(ix.row(), ix.column()) for ix in table.selectedIndexes()] if SaveIndexes else [(-1, -1)]
                }
    
    def load_table(self, data : dict):
        table : QTableWidget = self.findChild(QTableWidget, data["object_name"])
        realdata = data["data"]
        SaveIndexes = "SaveIndex" in self.savetables[table]
        SaveContent = "SaveContent" in self.savetables[table]
        lastselectedindexes = data["lastselectedindexes"] if SaveIndexes and "lastselectedindexes" in data.keys() else None

        if SaveContent:
            table.setRowCount(len(realdata))
            table.setColumnCount(len(realdata[0]) if realdata else 0)
            for row, row_data in enumerate(realdata):
                for col, cell in enumerate(row_data):
                    if cell is not None:
                        item = QTableWidgetItem(cell["text"])
                        item.setData(256, cell["user_data"])
                        table.setItem(row, col, item)
        if lastselectedindexes and lastselectedindexes != (-1,-1):
            table.clearSelection()
            for row, col in lastselectedindexes:
                idx = table.model().index(row, col)
                table.blockSignals(True)
                #table.selectionModel().select(
                #    idx,
                #    QItemSelectionModel.Select | QItemSelectionModel.Rows  # oder .Columns / .NoUpdate
                #)
                table.setCurrentIndex(idx)
                table.blockSignals(False)

    def save_lineEdit(self, lineEdit: QLineEdit):
        return {
                    "object_name": lineEdit.objectName(),  # eindeutiger Name
                    "data": lineEdit.text()
                }
    
    def load_lineEdit(self, data):
        lineEdit : QLineEdit = self.findChild(QLineEdit, data["object_name"])
        realdata = data["data"]
        lineEdit.setText(realdata)

    def save_users_widgetinfos(self):
        global linecolor, pointcolor
        tablecontent = [self.save_table(table=tbl) for tbl in self.savetables.keys()]
        lineeditcontent = [self.save_lineEdit(lnEd) for lnEd in self.savelineedits]
        allcont =   {
                    "tablecontent" : tablecontent,
                    "lineeditcontent" : lineeditcontent,
                    "pointandlinecolors" : (pointcolor, linecolor),
                    "Flowmap Color Channel X" : self.OpenGL_MainImage.ColorChannelX,
                    "Flowmap Color Channel Y" : self.OpenGL_MainImage.ColorChannelY
                    }

        with open(self.savefilelocation, 'wb') as handle:
            pickle.dump(allcont, handle, protocol=pickle.HIGHEST_PROTOCOL)

    def load_users_widgetinfos(self):
        global linecolor, pointcolor
        if os.path.exists(self.savefilelocation):
            try:
                with open(self.savefilelocation, 'rb') as handle:
                    allcont = pickle.load(handle)
                if "Flowmap Color Channel X" in allcont: self.OpenGL_MainImage.ColorChannelX = allcont["Flowmap Color Channel X"]
                if "Flowmap Color Channel Y" in allcont: self.OpenGL_MainImage.ColorChannelY = allcont["Flowmap Color Channel Y"]

                tablecontent = allcont["tablecontent"]
                lineeditcontent = allcont["lineeditcontent"]
                if "pointandlinecolors" in allcont:
                    pointcolor, linecolor = allcont["pointandlinecolors"]
                for lineeditdata in lineeditcontent:
                    self.load_lineEdit(lineeditdata)

                self.update_SelectFiles()
                
                for tabledata in tablecontent:
                    self.load_table(tabledata)

                self.file_selected()

            except Exception as e:
                print(f"Error in load_users_widgetinfo: ({e})")


    def closeEvent(self, event):
        self.stop_timer(self.OpenGL_MainImage.anim_timer)
        self.save_users_widgetinfos()
        self.managerqueuein.put({"stop" : 1})        
        super().closeEvent(event)

## UI Class because ui_ImageToFlowmap is generated by qt designer and will be overwritten by design changes ##### End
possibleParametersEditUITypes = Dict[str, Union[str, int, float, Tuple[Union[int,float],Union[int,float],Union[int,float]], Dict[str, Union[int, float, Tuple[Union[int,float],Union[int,float],Union[int,float]]]]]]
class ParametersEditUI(QDialog, Ui_ParameterEdit):
    def __init__(self, Parameters : possibleParametersEditUITypes):
        super().__init__()
        self.setupUi(self)
        self.OGParameters = Parameters
        self.table_ParametersValues.setRowCount(len(Parameters))
        self.table_ParametersValues.setColumnCount(2)
        self.table_ParametersValues.setHorizontalHeaderLabels(["Parameter Name", "Value"])

        row = 0
        for Parname, Parval in Parameters.items():
            # Name in Spalte 0
            item = QTableWidgetItem(str(Parname))
            item.setFlags(Qt.ItemIsEnabled)  # nur Anzeige, nicht editierbar
            self.table_ParametersValues.setItem(row, 0, item)
            #print(f"parname:({Parname}) to row ({row})")
            # Value-Editor in Spalte 1
            if isinstance(Parval, tuple):
                self.table_ParametersValues.setRowCount(self.table_ParametersValues.rowCount() + max(0, len(Parval) - 1))
                for rowadd, subval in enumerate(Parval):
                    editor = self.get_editor(subval)
                    self.table_ParametersValues.setCellWidget(row + rowadd, 1, editor)
                row += rowadd + 1
                continue
            elif isinstance(Parval, dict):
                self.table_ParametersValues.setColumnCount(3)
                self.table_ParametersValues.setRowCount(self.table_ParametersValues.rowCount() + max(0, len(Parval) - 1))
                for subrow, (subParname, subParval) in enumerate(Parval.items()):
                    item = QTableWidgetItem(str(subParname))
                    item.setFlags(Qt.ItemIsEnabled)  # nur Anzeige, nicht editierbar
                    self.table_ParametersValues.setItem(row + subrow, 1, item)
                    if isinstance(subParval, tuple):
                        self.table_ParametersValues.setRowCount(self.table_ParametersValues.rowCount() + max(0, len(subParval) - 1))
                        for rowadd, subval in enumerate(subParval):
                            editor = self.get_editor(subval)
                            self.table_ParametersValues.setCellWidget(row + subrow + rowadd, 2, editor)
                        row += rowadd
                    else:
                        editor = self.get_editor(subParval)                        
                        self.table_ParametersValues.setCellWidget(row + subrow, 2, editor)
                row += subrow
            else:
                editor = self.get_editor(Parval)
                self.table_ParametersValues.setCellWidget(row, 1, editor)
            row += 1
        self.Button_Save.clicked.connect(self.SaveClicked)
        self.Button_Discard.clicked.connect(self.DiscardClicked)
        if self.table_ParametersValues.columnCount() == 3:
            self.table_ParametersValues.setHorizontalHeaderLabels(["Parameter Name", "Sub-Parameter/Value", "Value"])

    def get_editor(self, Val):
        editor = QLineEdit()
        if isinstance(Val, int):
            editor.setText(str(Val))
            editor.setValidator(QtGui.QIntValidator())
        elif isinstance(Val, float):
            class FlexibleDoubleValidator(QtGui.QDoubleValidator):
                def __init__(self, bottom=0.0, top=100.0, decimals=3, parent=None):
                    super().__init__(bottom, top, decimals, parent)
                    self.setNotation(QtGui.QDoubleValidator.StandardNotation)
                    self.setLocale(QLocale(QLocale.English))  # erlaubt '.'
                def validate(self, input_str, pos):
                    # Ersetze Komma durch Punkt, bevor Standardprüfung greift
                    input_str = input_str.replace(',', '.')
                    return super().validate(input_str, pos)
                def fixup(self, input_str):
                    return input_str.replace(',', '.')
            editor.setText(str(Val))
            validator = FlexibleDoubleValidator(decimals=4)
            editor.setValidator(validator)
        else:  # string oder sonstiges
            editor.setText(str(Val))
        return editor
    
    def SaveClicked(self):
        self.accept()

    def DiscardClicked(self):
        self.reject()

    def get_parameters(self) -> possibleParametersEditUITypes:
        result: possibleParametersEditUITypes = {}
        
        row = -1
        for rx in range(self.table_ParametersValues.rowCount()):
            row += 1
            if row == self.table_ParametersValues.rowCount(): break
            name_item = self.table_ParametersValues.item(row, 0)
            subname_val = self.table_ParametersValues.item(row, 1)
            sub_value = self.table_ParametersValues.cellWidget(row, 2)
            if sub_value: #-> subvalue means we have a dictionary
                tdict = {}
                lastnextsubname_valtext = ""
                broke = False
                for subrow in range(row, self.table_ParametersValues.rowCount()):
                    nextname_item = self.table_ParametersValues.item(subrow, 0)
                    nextsubname_val = self.table_ParametersValues.item(subrow, 1)
                    nextsub_value = self.table_ParametersValues.cellWidget(subrow, 2)
                    if not subrow == row and nextname_item: #-> means we have the next mainparameter
                        #tdict[nextsubname_val.text()] = nextsub_value.text()
                        result[name_item.text()] = tdict
                        row = subrow - 1 
                        broke = True
                        break
                    else:
                        if nextsubname_val: #-> means we have the next dictionary item
                            lastnextsubname_valtext = nextsubname_val.text()
                            tp = get_type_from_widget_validator(nextsub_value)
                            tdict[nextsubname_val.text()] = tp(nextsub_value.text())
                        else:
                            tp = get_type_from_widget_validator(nextsub_value)
                            newparams = tdict[lastnextsubname_valtext] if type(tdict[lastnextsubname_valtext]) == tuple else tuple([tdict[lastnextsubname_valtext]])
                            tdict[lastnextsubname_valtext] = (*newparams, tp(nextsub_value.text()))
                if broke:
                    continue
                row = subrow
                result[name_item.text()] = tdict
            else:
                editor = self.table_ParametersValues.cellWidget(row, 1)
                if not name_item and not editor:
                    continue
                if name_item:
                    lastnextsubname_valtext = name_item.text()
                tp = get_type_from_widget_validator(editor)
                if lastnextsubname_valtext in result:
                    newparams = result[lastnextsubname_valtext] if type(result[lastnextsubname_valtext]) == tuple else tuple([result[lastnextsubname_valtext]])
                    result[lastnextsubname_valtext] = (*newparams, tp(editor.text()))
                else:
                    result[lastnextsubname_valtext] = tp(editor.text())
        return result

def get_type_from_widget_validator(widget):
    try:
        a = widget.validator()
        if a:
            return get_type_from_validator(a)
    except:
        pass
    return "unknown"

def get_type_from_validator(validator):
    if isinstance(validator, QtGui.QIntValidator):
        return int
    elif isinstance(validator, QtGui.QDoubleValidator):
        return float
    elif validator is None:
        return str
    else:
        return "unknown"


if __name__ == "__main__":
    app = QApplication([])
    app.setStyle(QStyleFactory.create("Fusion"))
    mpmgr : SyncManager = Manager()
    ImgToFlowmapUI = ImageToFlowmapUI()    
    app.exec()
#addlog("debug", f"✅ All Code in {sys.modules[__name__].__file__} executed!")