from PySide6.QtCore import Qt, QSignalBlocker, QTimer
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import QScrollBar

## UI Class because ui_ImageToFlowmap is generated by qt designer and will be overwritten by design changes
from OpenGL.GL import *
from OpenGL.GLU import *
import cv2
import numpy as np


import math, os
from time import time

from typing import Union, Literal, Tuple

import colorsys, hashlib

from sympy import Point

from ImageToFlowmap.FileHandler import SaveFlowmap, get_datatype
from ImageToFlowmap.networker_4 import junction, pointpath
from ImageToFlowmap.networker_5 import flowmapobj

##GLSL Start

# GLSL (klein, kompatibel)
#Imagelayer
STATIC_VERT_SRC = """
#version 330 core
layout(location = 0) in vec2 aPos;   // Quad-Position
layout(location = 1) in vec2 aTex;   // TexCoord

uniform mat4 uMVP;                   // Projection * View * Model
uniform float uZ;                    // Layer z-Wert

out vec2 vTex;

void main() {
    vTex = vec2(aTex.x, 1.0 - aTex.y);
    gl_Position = uMVP * vec4(aPos, uZ, 1.0);
}
"""
STATIC_FRAG_SRC = """
#version 330 core
in vec2 vTex;
out vec4 FragColor;

uniform sampler2D uTex;
uniform vec4 uColor;
uniform float uAlpha;
uniform bool uBlingBling;
uniform float uTime;

void main() {
    vec4 texColor = texture(uTex, vTex);
    vec4 color = texColor * uColor;
    color.a *= uAlpha;

    if (color.a < 0.01) discard;

    if (uBlingBling) {
        // Puls
        vec2 offsets[9] = vec2[](
        vec2(-1.0, -1.0), vec2(0.0, -1.0), vec2(1.0, -1.0),
        vec2(-1.0,  0.0), vec2(0.0,  0.0), vec2(1.0,  0.0),
        vec2(-1.0,  1.0), vec2(0.0,  1.0), vec2(1.0,  1.0)
        );
        float weight[9] = float[](0.05, 0.1, 0.05, 0.1, 0.4, 0.1, 0.05, 0.1, 0.05);

        vec4 accum = vec4(0.0);
        for (int i = 0; i < 9; ++i)
            accum += texture(uTex, vTex + offsets[i] * 0.002) * weight[i]; // 0.002 ≈ Blur-Radius

        float pulse = 0.5 + 0.5 * sin(uTime * 6.0);
        vec4 glow = accum * uColor * pulse * 1.5;
        glow.a = clamp(glow.a, 0.0, 1.0); // Alpha auch weich

        // Mischung: Original + Glow
        FragColor = vec4(color.rgb + glow.rgb, color.a + glow.a * 0.8);
    }
    else {
        FragColor = color;
    }
}
"""
#Pointpatharrows
ARROWS_VERT_SRC = """
// Uniforms:
uniform mat4 uMVP;
uniform float uZ;
uniform float uLayerHeight;

// Attribute/Instancing:
layout(location=0) in vec2 aLocalPos;  // Pfeilshape, zentriert
layout(location=1) in vec2 iPos;       // Pfadposition
layout(location=2) in vec2 iDir;       // Richtung
layout(location=3) in float iSize;     // Pfeilgröße

void main() {
    // Pfad-Y flippen
    vec2 posFlip = vec2(iPos.x, uLayerHeight - iPos.y);

    // iDir ebenfalls spiegeln (Y-Achse invertieren)
    vec2 dirFlip = vec2(iDir.x, -iDir.y);

    // senkrecht zur Richtung
    vec2 perp = vec2(-dirFlip.y, dirFlip.x);

    // Pfeil-Mittelpunkt transformieren
    vec2 world = posFlip
            + dirFlip * (aLocalPos.y * iSize)
            + perp    * (aLocalPos.x * iSize);

    gl_Position = uMVP * vec4(world, uZ, 1.0);
}
"""
ARROWS_FRAG_SRC = """
#version 330 core
out vec4 FragColor;

uniform sampler2D uTex;
uniform vec4 uColor;       // Basisfarbe des Arrows
uniform float uAlpha;      // Transparenz
uniform bool uBlingBling;  // Selection glow
uniform float uTime;       // Zeit für Puls

in vec2 vTex; // Falls UVs vorhanden sind

void main() {
    vec4 color = uColor;

    if (uBlingBling) {
        // Puls
        vec2 offsets[9] = vec2[](
        vec2(-1.0, -1.0), vec2(0.0, -1.0), vec2(1.0, -1.0),
        vec2(-1.0,  0.0), vec2(0.0,  0.0), vec2(1.0,  0.0),
        vec2(-1.0,  1.0), vec2(0.0,  1.0), vec2(1.0,  1.0)
        );
        float weight[9] = float[](0.05, 0.1, 0.05, 0.1, 0.4, 0.1, 0.05, 0.1, 0.05);

        vec4 accum = vec4(0.0);
        for (int i = 0; i < 9; ++i)
            accum += texture(uTex, vTex + offsets[i] * 0.002) * weight[i]; // 0.002 ≈ Blur-Radius

        float pulse = 0.5 + 0.5 * sin(uTime * 6.0);
        vec4 glow = accum * uColor * pulse * 1.5;
        glow.a = clamp(glow.a, 0.0, 1.0); // Alpha auch weich

        // Mischung: Original + Glow
        FragColor = vec4(color.rgb + glow.rgb, color.a + glow.a * 0.8);
    }
    else {
        // Additive Mischung findet in OpenGL statt via glBlendFunc(GL_ONE, GL_ONE)
        FragColor = vec4(color.rgb, uAlpha);
    }
}
"""
#Flowmap
FLOW_VERT_SRC = """
#version 330 core
layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aTex;

uniform mat4 uMVP;
uniform float uZ;

out vec2 vTex;

void main() {
    vTex = vec2(aTex.x, 1.0 - aTex.y); // UV invertieren
    gl_Position = uMVP * vec4(aPos, uZ, 1.0);
}
"""
FLOW_FRAG_SRC = """
#version 330 core
in vec2 vTex;
out vec4 FragColor;

uniform sampler2D uTex;
uniform sampler2D uFlowmap;
uniform sampler2D uPanner;


uniform float uOffset;
uniform float uAlpha;
uniform vec2 uPanning;
uniform bool uBlingBling;     // Selection
uniform float uTime;        // Time for blingbling
uniform vec4 uColor; // Grundfarbe
uniform int uDrawAsColor;   //-> draw as flowmap color
uniform int  uFlowType;  // 0=Water, 1=Lava, 2=Fog
uniform ivec3 uMaskX; // z.B. (1,0,0) für r, (0,1,0) für g, (0,0,-1) für -b
uniform ivec3 uMaskY;

void main() {
    vec4 flow = texture(uFlowmap, vTex);
    //flow.y = 1-flow.y;
    vec4 color;
    float mask = flow.a;
    if (uDrawAsColor == 0) {
        vec2 dir = normalize(vec2(dot(flow.rgb, uMaskX), dot(flow.rgb, uMaskY)));
        //vec2 dir = normalize(vec2(flow.r, flow.g) * 2.0 - 1.0);
                

        // --- Water ---
        if (uFlowType == 0) {
            //mask = smoothstep(0.05, 1.0, mask);
            vec2 uv1 = fract(vTex + dir * uOffset * uPanning);
            vec2 uv2 = fract(vTex + dir * (uOffset + 0.5) * uPanning);
            vec4 t1 = texture(uPanner, uv1);
            vec4 t2 = texture(uPanner, uv2);
            float blend = 0.5 + 0.5 * sin(uOffset * 3.1415);
            color = mix(t1, t2, blend) * uColor;
        }

        // --- Lava ---
        else if (uFlowType == 1) {
            //mask = pow(mask, 2.0);
            vec2 uv1 = fract(vTex + dir * uOffset * uPanning * 1.5);
            vec2 uv2 = fract(vTex + dir * (uOffset + 0.33) * uPanning * 1.5);
            vec4 t1 = texture(uPanner, uv1);
            vec4 t2 = texture(uPanner, uv2);
            float flicker = 0.5 + 0.5 * sin(uOffset * 12.0);
            color = pow(mix(t1, t2, flicker) * uColor, vec4(1.2));
        }

        // --- Fog ---
        else if (uFlowType == 2) {
            dir *= 0.2;
            //mask = smoothstep(0.0, 1.0, mask);
            vec2 uv1 = fract(vTex + dir * uOffset * uPanning);
            vec2 uv2 = fract(vTex - dir * (uOffset + 0.25) * uPanning);
            vec4 t1 = texture(uPanner, uv1);
            vec4 t2 = texture(uPanner, uv2);
            float blend = 0.5 + 0.5 * sin(uOffset * 3.1415);
            color = mix(t1, t2, blend) * uColor;
            color.rgb = mix(color.rgb, vec3(1.0), 0.2);
        }    
    }
    else {
        color = flow;
    }
    color.a *= mask * uAlpha;
    if (uBlingBling) {
        // Puls
        vec2 offsets[9] = vec2[](
        vec2(-1.0, -1.0), vec2(0.0, -1.0), vec2(1.0, -1.0),
        vec2(-1.0,  0.0), vec2(0.0,  0.0), vec2(1.0,  0.0),
        vec2(-1.0,  1.0), vec2(0.0,  1.0), vec2(1.0,  1.0)
        );
        float weight[9] = float[](0.05, 0.1, 0.05, 0.1, 0.4, 0.1, 0.05, 0.1, 0.05);

        vec4 accum = vec4(0.0);
        for (int i = 0; i < 9; ++i)
            accum += texture(uTex, vTex + offsets[i] * 0.002) * weight[i]; // 0.002 ≈ Blur-Radius

        float pulse = 0.5 + 0.5 * sin(uTime * 6.0);
        vec4 glow = accum * uColor * pulse * 1.5;
        glow.a = clamp(glow.a, 0.0, 1.0); // Alpha auch weich

        // Mischung: Original + Glow
        FragColor = vec4(color.rgb + glow.rgb, color.a + glow.a * 0.8);
    }
    else {
        FragColor = color;
    }
}
"""

baselinecolor = {"unselected" : (0.3,0.3,0.3), "halfselected" : (0.5,0.5,1), "selected" : (0.7,1,0.7)}
basepointcolor = {"unselected" : (0.3,0.5,1), "halfselected" : (0.5,1,0.5), "selected" : (1,0.7,0.7)}

linecolor = baselinecolor   #-> gets updated from imagetoflowmap
pointcolor = basepointcolor

##GLSL End
def upload_mat4(loc, mat):
    # mat ist NumPy row-major (wie üblich). OpenGL erwartet column-major -> transpose.
    arr = np.ascontiguousarray(mat.T, dtype=np.float32)
    glUniformMatrix4fv(loc, 1, GL_FALSE, arr)
def translate(x, y, z=0.0):
    m = np.identity(4, dtype=np.float32)
    m[0, 3] = x
    m[1, 3] = y
    m[2, 3] = z
    return m

def scale(sx, sy, sz=1.0):
    m = np.identity(4, dtype=np.float32)
    m[0, 0] = sx
    m[1, 1] = sy
    m[2, 2] = sz
    return m

def ortho_matrix(left, right, bottom, top, near, far):
    return np.array([
        [2/(right-left), 0, 0, -(right+left)/(right-left)],
        [0, 2/(top-bottom), 0, -(top+bottom)/(top-bottom)],
        [0, 0, -2/(far-near), -(far+near)/(far-near)],
        [0, 0, 0, 1]
    ], dtype=np.float32)

class BaseLayer():
    def __init__(self, name, height, width, z_depth, alpha, selected):
        self.name = name
        self.height = height
        self.width = width
        self.depth = z_depth
        self.alpha = alpha
        self.selected = selected

class ImageLayer(BaseLayer):
    def __init__(self, name, texture : np.uintc, height, width, z_depth, alpha, ogimg, selected = False, speed = 1.0, color = (1,1,1)):
        super().__init__(name, height, width, z_depth, alpha, selected)
        self.texture : np.uintc = texture
        self.ogimage = ogimg
        self.speed = speed
        self.color = color

class PathLayer(ImageLayer):    
    def __init__(self, name, pointpath : pointpath, height, width, z_depth, alpha, ogimg, selected, offset = 0.0, speed = 0.01, color = (0,0,0)):
        super().__init__(name, pointpath.texture, height, width, z_depth, alpha, ogimg, selected, speed, color)
        self.pointpath = pointpath
        self.offset = offset

class PointLayer(ImageLayer):
    def __init__(self, name, obj : junction, height, width, z_depth, alpha, ogimg, selected = False, speed = 1.0, color = (1,0,0)):
        super().__init__(name, obj.texture, height, width, z_depth, alpha, ogimg, selected, speed, color)
        self.pointobj = obj

drawmodes = Literal["water", "lava", "fog"]
drawmodemap = {x : i for i, x in enumerate(drawmodes.__args__)}
class FlowmapLayer(ImageLayer):
    def __init__(self, name, obj : flowmapobj, height, width, z_depth, alpha, ogimg, selected, offset = 0.0, speed=1.0, color = (0,0,0), drawmode : drawmodes = "water", drawAsColor = 0):
        super().__init__(name, obj.texture, height, width, z_depth, alpha, ogimg, selected, speed, color)
        self.pannertexture = obj.pannertexture
        self.panning_u = obj.panning_u
        self.panning_v = obj.panning_v
        self.offset = offset
        self.flowmapobj = obj
        self.drawmode = drawmode
        self.set_drawmode(drawmode)
        self.drawAsColor = drawAsColor

    def set_drawmode(self, newdrawmode : drawmodes):
        if not newdrawmode in drawmodemap: return False
        self.drawmode = newdrawmode 
        self.rdrawmode = drawmodemap[newdrawmode]

class LayerCollection:
    def __init__(self, layertype : Union[BaseLayer,ImageLayer, PathLayer, PointLayer, FlowmapLayer]):
        self._layers = {}
        self.layertype = layertype

    def __getitem__(self, key: str | object) -> ImageLayer:
        if type(key) == str:
            return self._layers[key]
        elif isinstance(key, PathLayer):
            for v in self._layers.values():
                if v.pointpath == key:
                    return v
        elif isinstance(key, FlowmapLayer):
            for v in self._layers.values():
                if v.ogimage == key:
                    return v
        elif isinstance(key, ImageLayer):
            for v in self._layers.values():
                if v.ogimage == key:
                    return v
        elif isinstance(key, PointLayer):
            for v in self._layers.values():
                if v.points == key:
                    return v
        else:
            raise Exception(f"Error in Layercollection ({self}) __getitem__: unknown keytype: ({type(key)})")
        return None
    
    def __setitem__(self, key: str, value):               
        if self.layertype == ImageLayer:
            self._layers[key] = ImageLayer(key, *value)
        elif self.layertype ==  PathLayer:
            self._layers[key] = PathLayer(key, *value)
        elif self.layertype ==  PointLayer:
            self._layers[key] = PointLayer(key, *value)
        elif self.layertype ==  FlowmapLayer:
            self._layers[key] = FlowmapLayer(key, *value)
            

    def __delitem__(self, key: str):
        del self._layers[key]

    def __iter__(self):
        return iter(self._layers)

    def __len__(self):
        return len(self._layers)

    def items(self):
        return self._layers.items()

    def values(self):
        return self._layers.values()

    def keys(self):
        return self._layers.keys()
    
layertypes = Union[BaseLayer, ImageLayer, PathLayer, PointLayer, FlowmapLayer]

class MyGL(QOpenGLWidget):
    def __init__(self, Scrollbar_Horizontal = None, Scrollbar_Vertical = None, Scrollbar_Zoom = None, Scrollbar_Zoom_doubleSpinBox = None, Scrollbar_OverallSpeed = None, Scrollbar_OverallSpeed_doubleSpinBox  = None):
        self.initialized = False
        if not hasattr(self, "layers"):
            super().__init__()

        self.reset_layercollections()

        self.offset_x = 0
        self.offset_y = 0 
        self.zoom     = 1
        self.OG_OpenGL_width    = self.width()
        self.OG_OpenGL_height   = self.height()

        self.Scrollbar_Horizontal   : QScrollBar    = Scrollbar_Horizontal
        self.Scrollbar_Vertical     : QScrollBar    = Scrollbar_Vertical
        self.Scrollbar_Zoom         : QScrollBar    = Scrollbar_Zoom

        self.Scrollbar_OverallSpeed : QScrollBar    = Scrollbar_OverallSpeed

        self.isupdating = False
        self.overallspeed = 1.0

        #Scrollbars of OpenGL_MainImage
        if self.Scrollbar_Horizontal:   self.Scrollbar_Horizontal.valueChanged.connect(self.on_scroll_h)
        if self.Scrollbar_Vertical:     self.Scrollbar_Vertical.valueChanged.connect(self.on_scroll_v)

        if self.Scrollbar_Zoom:         
            self.Scrollbar_Zoom.valueChanged.connect(self.on_scroll_zoom)
            if not Scrollbar_Zoom_doubleSpinBox:
                if hasattr(self.Scrollbar_Zoom, "doubleSpinBox"):
                    self.Scrollbar_Zoom_doubleSpinBox = self.Scrollbar_Zoom.doubleSpinBox
            elif Scrollbar_Zoom_doubleSpinBox:
                self.Scrollbar_Zoom_doubleSpinBox = Scrollbar_Zoom_doubleSpinBox
                self.Scrollbar_Zoom.doubleSpinBox = Scrollbar_Zoom_doubleSpinBox
                self.Scrollbar_Zoom.doubleSpinBox.valueChanged.connect(self.on_scroll_zoom_doublespinbox)

        if self.Scrollbar_OverallSpeed:
            self.Scrollbar_OverallSpeed.valueChanged.connect(self.on_scroll_speed)
            if not Scrollbar_OverallSpeed_doubleSpinBox:
                if hasattr(self.Scrollbar_OverallSpeed, "doubleSpinBox"):
                    self.Scrollbar_OverallSpeed_doubleSpinBox = self.Scrollbar_OverallSpeed.doubleSpinBox
            elif Scrollbar_OverallSpeed_doubleSpinBox:
                self.Scrollbar_OverallSpeed_doubleSpinBox = Scrollbar_OverallSpeed_doubleSpinBox
                self.Scrollbar_OverallSpeed.doubleSpinBox = Scrollbar_OverallSpeed_doubleSpinBox
                self.Scrollbar_OverallSpeed.doubleSpinBox.valueChanged.connect(self.on_scroll_speed_doublespinbox)

        ## End Scrollbars

        ## Flowmap color channels
        self.ColorChannelX = (1,0,0)
        self.ColorChannelY = (0,1,0)

        ## Panningtexture
        self.pannertexture : np.ndarray = None
        self.init_pannertexture()
        ## End Panningtexture
        
        self.init_set_zoom_ranges()
        self.init_set_speed_ranges()

        self.anim_timer = QTimer(self)
        self.anim_timer.timeout.connect(self.tick)  # paintGL wird neu aufgerufen
        self.refreshrate = 30
        QTimer.singleShot(1000, lambda : self.anim_timer.start(self.refreshrate))  # ~33 FPS, kannst du anpassen
        self.timedelta = 0
        self.last_update = time()
        self.doupdates = True

    def init_pannertexture(self):
        self.pannertexture = self.load_image_cv2(os.path.join(os.path.dirname(__file__), "PanningTexture", "panning_standard.png"))
    
    def change_refreshrate(self, value : int):
        self.refreshrate = value
        self.anim_timer.setInterval(value)

    def setLayout(self, arg__1):
        rt = super().setLayout(arg__1)
        self.OG_OpenGL_width = self.width()
        self.OG_OpenGL_height = self.height()
        return rt
    
    def initializeGL(self):
        glClearColor(0.2, 0.2, 0.2, 1.0)
        self.basicprogram = self.createShaderProgram(STATIC_VERT_SRC, STATIC_FRAG_SRC)
        self.flowmapprogram = self.createShaderProgram(FLOW_VERT_SRC, FLOW_FRAG_SRC)
        self.arrowprogram = self.createShaderProgram(ARROWS_VERT_SRC, ARROWS_FRAG_SRC)
        self._init_quad()
        self._init_arrow_renderer()
        glEnable(GL_DEPTH_TEST)
        self.initialized = True

    def resizeGL(self, w, h):
        self.OG_OpenGL_width = self.width()
        self.OG_OpenGL_height = self.height()
        # w,h sind framebuffer-pixel hier (QOpenGLWidget liefert das)
        glViewport(0, 0, self.OG_OpenGL_width, self.OG_OpenGL_height)
        glMatrixMode(GL_PROJECTION); glLoadIdentity()
        # Top-left origin (Qt): y wächst nach unten
        gluOrtho2D(0, self.OG_OpenGL_width, 0, self.OG_OpenGL_height)
        glMatrixMode(GL_MODELVIEW); glLoadIdentity()

        # Bild anpassen
        if hasattr(self, "img_width") and hasattr(self, "img_height"):
            scale_x = self.OG_OpenGL_width / self.img_width
            scale_y = self.OG_OpenGL_height / self.img_height
            self.zoom = min(scale_x, scale_y)   # fit to viewport, kein Stretch
            self.offset_x = (self.OG_OpenGL_width - self.img_width * self.zoom) / 2
            self.offset_y = (self.OG_OpenGL_height - self.img_height * self.zoom) / 2
            self.update_zoom_widgets()
            self.sync_scrollbars(zoomchanged=True)
        self.update()

    def tick(self):
        #print("tick")
        if self.doupdates and self.initialized:
            self.update()
        #print(f"tick; deltat: {time() - self.last_update}")
        
    def _init_arrow_renderer(self):
        # Basis-Dreieck (ein Pfeil)
        height, width = 1.1, 0.6
        arrow_shape = np.array([
            [-width/2, -height/2],  # links unten
            [ width/2, -height/2],  # rechts unten
            [ 0,       height/2],   # Spitze oben
        ], dtype=np.float32)

        vao = glGenVertexArrays(1)
        vbo = glGenBuffers(1)
        instance_vbo = glGenBuffers(1)

        glBindVertexArray(vao)

        # Basis-Dreieck VBO
        glBindBuffer(GL_ARRAY_BUFFER, vbo)
        glBufferData(GL_ARRAY_BUFFER, arrow_shape.nbytes, arrow_shape, GL_STATIC_DRAW)
        glEnableVertexAttribArray(0)
        glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, None)

        # Instanz-Attribute (pos.x, pos.y, dir.x, dir.y, size)
        glBindBuffer(GL_ARRAY_BUFFER, instance_vbo)
        stride = 5 * 4  # 5 floats = 20 bytes

        # iPos (location=1)
        glEnableVertexAttribArray(1)
        glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, stride, ctypes.c_void_p(0))
        glVertexAttribDivisor(1, 1)

        # iDir (location=2)
        glEnableVertexAttribArray(2)
        glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, stride, ctypes.c_void_p(8))
        glVertexAttribDivisor(2, 1)

        # iSize (location=3)
        glEnableVertexAttribArray(3)
        glVertexAttribPointer(3, 1, GL_FLOAT, GL_FALSE, stride, ctypes.c_void_p(16))
        glVertexAttribDivisor(3, 1)

        glBindVertexArray(0)

        self.arrowvao = vao
        self.arrowvbo = vbo
        self.arrow_instance_vbo = instance_vbo
        
    def _init_quad(self):
        # Quad mit Position (x,y) und TexCoord (u,v)
        # Normalisiert von (0,0) bis (1,1), Breite/Höhe skalierst du per MVP
        vertices = np.array([
            # x, y,   u, v
            0.0, 0.0, 0.0, 0.0,
            1.0, 0.0, 1.0, 0.0,
            1.0, 1.0, 1.0, 1.0,
            0.0, 1.0, 0.0, 1.0,
        ], dtype=np.float32)

        indices = np.array([0, 1, 2, 0, 2, 3], dtype=np.uint32)

        # VAO
        vao = glGenVertexArrays(1)
        glBindVertexArray(vao)

        # VBO
        vbo = glGenBuffers(1)
        glBindBuffer(GL_ARRAY_BUFFER, vbo)
        glBufferData(GL_ARRAY_BUFFER, vertices.nbytes, vertices, GL_STATIC_DRAW)

        # EBO
        ebo = glGenBuffers(1)
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo)
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.nbytes, indices, GL_STATIC_DRAW)

        # Attribut 0 → Position (vec2)
        glEnableVertexAttribArray(0)
        glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 4 * vertices.itemsize, ctypes.c_void_p(0))

        # Attribut 1 → TexCoord (vec2)
        glEnableVertexAttribArray(1)
        glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 4 * vertices.itemsize, ctypes.c_void_p(2 * vertices.itemsize))

        glBindVertexArray(0)

        # speichern, damit du es in _draw_image_layer nutzen kannst
        self.quadvao = vao
        self.quadvbo = vbo
        self.quadebo = ebo

    def clear(self, clearzoom = False):
        self.reset_layercollections()
        self.offset_x = 0.0
        self.offset_y = 0.0
        if clearzoom: self.zoom = 1.0
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        self.update()

    def reset_layercollections(self, ltype : Union[layertypes, Literal["All"]] = "All"):
        if ltype == "All":
            self.imagelayers = LayerCollection(layertype=ImageLayer)
            self.pathlayers = LayerCollection(layertype=PathLayer)
            self.pointlayers = LayerCollection(layertype=PointLayer)
            self.flowmaplayers = LayerCollection(layertype=FlowmapLayer)
        elif ltype == ImageLayer:
            self.imagelayers    = LayerCollection(layertype=ImageLayer)
        elif ltype == PathLayer:
            self.pathlayers     = LayerCollection(layertype=PathLayer)
        elif ltype == PointLayer:
            self.pointlayers    = LayerCollection(layertype=PointLayer)
        elif ltype == FlowmapLayer:
            self.flowmaplayers  = LayerCollection(layertype=FlowmapLayer)

        self.layercollections = [self.imagelayers, self.pathlayers, self.pointlayers, self.flowmaplayers]

    def add_layer(self, layertype : layertypes, displayobj, layer_name : str, z_depth : int | float, alpha : float = 1.0, selected = False, offset = 0.0, speed = 1.0, color = (1,0,0), updateexisting = True):
        Did = isinstance(layertype, (FlowmapLayer, ImageLayer, PathLayer, PointLayer))
        layer = None
        if updateexisting or (not updateexisting and not layer_name in self.get_layercollection_by_type(layertype)):
            if layertype == FlowmapLayer:    
                layer = self.add_flowmap_layer(displayobj, layer_name, z_depth, alpha, selected, offset, speed, color)
            elif layertype == ImageLayer: 
                layer = self.add_image_layer(displayobj, layer_name, z_depth, alpha, selected, speed, color)
            elif layertype == PathLayer:
                layer = self.add_path_layer(displayobj, layer_name, z_depth, alpha, selected, offset, speed, color)
            elif layertype == PointLayer:
                layer = self.add_point_layer(displayobj, layer_name, z_depth, alpha, selected, speed, color)
        if Did:
            self.tick() #-> will only trigger if doupdates is enabled
        return layer
    
    def get_z_val(self, layer : BaseLayer, startz : float, zmultiplier : float, maxi : int):
        a = startz * zmultiplier
        if not layer.selected:
            return a
        else:
            return a + startz * (maxi - 1) + startz / 100
        
    def paintGL(self):
        if self.isupdating:
            return False
        self.isupdating = True
        
        self.timedelta = time() - self.last_update
        self.last_update = time()

        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)

        # Alpha-Blending global aktivieren
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

        # Ortho-Projektion vorbereiten
        w, h = self.width(), self.height()
        left   = -self.offset_x / self.zoom
        right  = (w - self.offset_x) / self.zoom
        bottom = -self.offset_y / self.zoom
        top    = (h - self.offset_y) / self.zoom
        proj = ortho_matrix(left, right, bottom, top, -1, 1)

        zmultiplier = 0
        startz = 0.001
        
        curlayer = sorted(self.imagelayers.items(), key=lambda x: x[1].depth)
        maxlayer = len(curlayer)
        selectedlayers = {}
        # --- Image-Layer ---
        for _, layer in curlayer:
            if layer.alpha > 0:
                z = self.get_z_val(layer, startz, zmultiplier, maxlayer)
                if layer.selected:
                    selectedlayers[layer] = z
                self._draw_image_layer(layer, z, proj, layer.selected, False)
                zmultiplier += 1

        curlayer = sorted(self.flowmaplayers.items(), key=lambda x: x[1].depth)
        maxlayer = len(curlayer)
        # --- Flowmap-Layer ---
        for _, layer in curlayer:
            if layer.alpha > 0:
                z = self.get_z_val(layer, startz, zmultiplier, maxlayer)
                if layer.selected:
                    selectedlayers[layer] = z
                self._draw_flowmap_layer(layer, z, proj, layer.selected, False)
                zmultiplier += 1

        curlayer = sorted(self.pathlayers.items(), key=lambda x: x[1].depth)
        maxlayer = len(curlayer)
        # --- Path-Layer ---
        for _, layer in curlayer:
            if layer.alpha > 0:
                z = self.get_z_val(layer, startz, zmultiplier, maxlayer)
                if layer.selected:
                    selectedlayers[layer] = z
                self._draw_path_layer(layer, z, proj, layer.selected, False)
                zmultiplier += 1

        curlayer = sorted(self.pointlayers.items(), key=lambda x: x[1].depth)
        maxlayer = len(curlayer)
        # --- Point-Layer ---
        for _, layer in curlayer:
            if layer.alpha > 0:
                z = self.get_z_val(layer, startz, zmultiplier, maxlayer)
                if layer.selected:
                    selectedlayers[layer] = z
                self._draw_point_layer(layer, z, proj, layer.selected, False)
                zmultiplier += 1

        glBlendFunc(GL_ONE, GL_ONE)
        #for layer, z in selectedlayers.items():
        #    z = z + 0.001 * z
        #    if type(layer) == ImageLayer:
        #        self._draw_image_layer(layer, z, proj, False, True)
        #    elif type(layer) == FlowmapLayer:
        #        self._draw_flowmap_layer(layer, z, proj, False, True)
        #    elif type(layer) == PathLayer:
        #        self._draw_path_layer(layer, z, proj, False, True)
        #    elif type(layer) == PointLayer:
        #        self._draw_point_layer(layer, z, proj, False, True)

        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

        glDisable(GL_BLEND)
        
        self.isupdating = False
    
    def get_layer_color_factor_sin(self, layer):
        return 1 + (math.sin(self.last_update * 5 * layer.speed) / 4)
    
    def _draw_image_layer(self, layer, z, proj, selected, blingbling = False):
        glUseProgram(self.basicprogram)

        # Model: skaliere Quad (0..1) auf Layergröße (width x height)
        model = scale(layer.width, layer.height, 1.0)

        # Ortho-Projektion * Model
        mvp = proj @ model

        # Uniforms
        upload_mat4(glGetUniformLocation(self.basicprogram, "uMVP"), mvp)
        glUniform1f(glGetUniformLocation(self.basicprogram, "uZ"), z)
        
        # Farbe (Selection / Normal)
        glUniform1i(glGetUniformLocation(self.basicprogram, "uBlingBling"), blingbling)
        glUniform1f(glGetUniformLocation(self.basicprogram, "uTime"), self.last_update)
        if selected:
            factor = self.get_layer_color_factor_sin(layer)
            color = tuple(x * factor for x in layer.color)
            glUniform4f(glGetUniformLocation(self.basicprogram, "uColor"), *color, 1.0)
        else:
            glUniform4f(glGetUniformLocation(self.basicprogram, "uColor"), *layer.color, 1.0)

        glUniform1f(glGetUniformLocation(self.basicprogram, "uAlpha"), layer.alpha)

        # Textur binden
        glActiveTexture(GL_TEXTURE0)
        glBindTexture(GL_TEXTURE_2D, layer.texture)
        glUniform1i(glGetUniformLocation(self.basicprogram, "uTex"), 0)

        # Zeichnen
        glBindVertexArray(self.quadvao)
        glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, None)
        glBindVertexArray(0)

        glUseProgram(0)

    def remove_layer(self, layertype : layertypes, layer_name, removeall = False):
        lcoll = self.get_layercollection_by_type(layertype)
        if not removeall:
            if layer_name in lcoll:
                lcoll.__delitem__(layer_name)
        else:
            lns = [layer for layer in lcoll if layer_name in layer]
            for layer in lns:
                lcoll.__delitem__(layer)
        self.update()
    
    def gen_image_tex_and_params(self, img):
        h, w = img.shape[0], img.shape[1]
        data = img.tobytes()#("raw", "RGBA", 0, -1)
        self.makeCurrent()
        tex = glGenTextures(1)
        glBindTexture(GL_TEXTURE_2D, tex)
        
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST)
        #glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
        #glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, data)
        return tex, h, w, img
    
    def add_image_layer(self, image, layer_name : str, z_depth : int | float, alpha : float = 1.0, selected = False, speed = 1.0, color = (1,1,1)):
        img = self.visualize_image_or_labels(image)
        tex, h, w, img = self.gen_image_tex_and_params(img)
        if len(self.imagelayers) == 0:
            self.img_width = w
            self.img_height = h
            self.resizeGL(self.width(), self.height())
        self.imagelayers[layer_name] = (tex, h, w, z_depth, alpha, img, selected, speed, color)
        return self.imagelayers[layer_name]
        #self.imagelayers[layer_name] = (tex, w, h, z_depth)

    def add_path_layer(self, ppath, layer_id, z_depth, alpha = 1.0, selected = False, offset = 0.0, speed = 1.0, color = (1,0,0)):
        tex, h, w, img = self.gen_image_tex_and_params(ppath.img)
        ppath.texture = tex
        self.pathlayers[layer_id] = [ppath, h, w, z_depth, alpha, img, selected, offset, speed, color]
        return self.pathlayers[layer_id]
        #print(f"MyGl: added :({name}), newlen: ({str(len(self.pathlayers))})")

    def _update_paths(self):
        for layer in self.path_layers.values():
            layer["offset"] += layer["speed"]
            if layer["offset"] > 1.0:
                layer["offset"] -= 1.0
        self.update()

    def _draw_path_layer(self, layer: PathLayer, z, proj, selected, blingbling = False):
        if not layer or layer.pointpath.texture is None:
            return

        # 1) Path-Image rendern
        self._draw_image_layer(layer, z, proj, selected, blingbling)

        # 2) Cache der Pfadpunkte (wie gehabt)
        cache = getattr(layer, "_cache", None)
        if cache is None:
            cache = layer._cache = {}

        pts = layer.pointpath.pts
        if pts.size == 0:
            return

        if ("pts" not in cache) or (cache["pts"].shape != pts.shape) or not np.all(cache["pts"] == pts):
            diffs = np.diff(pts, axis=0)
            seg_lens = np.linalg.norm(diffs, axis=1)
            cum_len = np.cumsum(seg_lens)
            cache.update({
                "pts": pts.copy(),
                "diffs": diffs,
                "seg_lens": seg_lens,
                "cum_len": cum_len,
                "total_len": cum_len[-1] if len(cum_len) else 0
            })

        diffs    = cache["diffs"]
        seg_lens = cache["seg_lens"]
        cum_len  = cache["cum_len"]
        total_len = cache["total_len"]

        if total_len <= 0:
            return
        
        lheight = layer.height
        
        # 3) Animation
        layer.offset += self.timedelta * self.overallspeed
        base_pos = (layer.offset * layer.speed * 8)

        # 4) Pfeile vorbereiten
        size = max(15 / self.zoom, 1.0)
        spacing = size * 4
        n_arrows = max(1, int(total_len / spacing))
        instances = []
        for k in range(n_arrows):
            arrow_pos = (base_pos + k*spacing) % total_len
            idx = np.searchsorted(cum_len, arrow_pos)
            
            # t innerhalb des Segments
            t = (arrow_pos - (cum_len[idx-1] if idx > 0 else 0)) / seg_lens[idx]
            
            # Weltposition und Richtung
            pos = pts[idx] + t * diffs[idx]        # immer vom Segmentstart
            if not (self.vx0 <= pos[0] <= self.vx1 and self.vy0 <= lheight-pos[1] <= self.vy1):
                continue
            iDir = diffs[idx] / seg_lens[idx]      # normiert → Pfeil zeigt vorwärts

            # Pfeilgröße dynamisch je nach Zoom
            size = max(15 / self.zoom, 1.0)

            # Instanz speichern: [x, y, dir_x, dir_y, size]
            instances.append([pos[0], pos[1], iDir[0], iDir[1], size])

        instances = np.array(instances, dtype=np.float32)

        # 5) Upload Instanzdaten
        glBindBuffer(GL_ARRAY_BUFFER, self.arrow_instance_vbo)
        glBufferData(GL_ARRAY_BUFFER, instances.nbytes, instances, GL_STREAM_DRAW)

        # 6) Shader nutzen
        glUseProgram(self.arrowprogram)
        
        #projectionmatrix
        mvp = proj
        upload_mat4(glGetUniformLocation(self.arrowprogram, "uMVP"), mvp)
        #z offset
        glUniform1f(glGetUniformLocation(self.arrowprogram, "uZ"), z + 0.002)
        #selection blingbling (partially gets bling bling in shader)
        glUniform1i(glGetUniformLocation(self.arrowprogram, "uBlingBling"), blingbling)
        glUniform1f(glGetUniformLocation(self.arrowprogram, "uTime"), self.last_update)
        glUniform1i(glGetUniformLocation(self.arrowprogram, "uTex"), 0)
        if selected:# Farbe (Selection / Normal)
            factor = self.get_layer_color_factor_sin(layer)
            color = tuple(x * factor for x in layer.color)
            glUniform4f(glGetUniformLocation(self.arrowprogram, "uColor"), *color, 1.0)
        else:
            glUniform4f(glGetUniformLocation(self.arrowprogram, "uColor"), *layer.color, 1.0)
        glUniform1f(glGetUniformLocation(self.arrowprogram, "uAlpha"), layer.alpha)
        glUniform1f(glGetUniformLocation(self.arrowprogram, "uLayerHeight"), layer.height)
        
        # 7) Zeichnen
        glBindVertexArray(self.arrowvao)
        glDrawArraysInstanced(GL_TRIANGLES, 0, 3, len(instances))
        glBindVertexArray(0)

        glUseProgram(0)

    def add_point_layer(self, pointobj, layer_name, z_depth, alpha, selected, speed, color):
        tex, h, w, img = self.gen_image_tex_and_params(pointobj.img)
        pointobj.texture = tex
        self.pointlayers[layer_name] = (pointobj, h, w, z_depth, alpha, img, selected, speed, color)
        return self.pointlayers[layer_name]
        
    def _draw_point_layer(self, pathlayer : PointLayer, z, proj, selected, blingbling = False):
        if not pathlayer or pathlayer.texture is None:
            return None
        
        self._draw_image_layer(pathlayer, z, proj, selected, blingbling)
    

    def gen_vao_vbo_ebo(self, flowmapobj, height, width):
        # Pixelkoordinaten-Quad passend zur Layer-Größe
        verts = np.array([
            0, 0, 0, 0,
            width, 0, 1, 0,
            width, height, 1, 1,
            0, height, 0, 1
        ], dtype=np.float32)

        indices = np.array([0,1,2,2,3,0], dtype=np.uint32)

        flowmapobj.vao = glGenVertexArrays(1)
        flowmapobj.vbo = glGenBuffers(1)
        flowmapobj.ebo = glGenBuffers(1)

        glBindVertexArray(flowmapobj.vao)

        glBindBuffer(GL_ARRAY_BUFFER, flowmapobj.vbo)
        glBufferData(GL_ARRAY_BUFFER, verts.nbytes, verts, GL_STATIC_DRAW)

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, flowmapobj.ebo)
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.nbytes, indices, GL_STATIC_DRAW)

        glVertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,16,ctypes.c_void_p(0))
        glEnableVertexAttribArray(0)
        glVertexAttribPointer(1,2,GL_FLOAT,GL_FALSE,16,ctypes.c_void_p(8))
        glEnableVertexAttribArray(1)

        glBindVertexArray(0)
    
    def add_flowmap_layer(self, flowmapo : flowmapobj, layer_id, z_depth, alpha, selected, offset, speed, color):
        tex, h, w, img = self.gen_image_tex_and_params((flowmapo.flowmap_image.astype(np.float64) /( 2**16-1)*(2**8-1)).astype(np.uint8))
        flowmapo.texture = tex
        tex, r, q, img = self.gen_image_tex_and_params(self.pannertexture)
        flowmapo.pannertexture = tex
        self.gen_vao_vbo_ebo(flowmapo, h, w)
        self.flowmaplayers[layer_id] = (flowmapo, h, w, z_depth, alpha, flowmapo.flowmap_image, selected, offset, speed, color)
        return self.flowmaplayers[layer_id]

    # Die Funktion (einfügen in deine Klasse)#
    def set_panner_u(self, newu):
        for fm in self.flowmaplayers.values():
            fm.panning_u = newu
    def set_panner_v(self, newv):
        for fm in self.flowmaplayers.values():
            fm.panning_v = newv
            
    def _draw_flowmap_layer(self, layer : FlowmapLayer, z : int, proj, selected, blingbling = False):

        layer.offset += self.timedelta * self.overallspeed #* 0.

        glUseProgram(self.flowmapprogram)

        # Model-Matrix (Quad 0..1 → Größe layer.width/height)
        model = scale(layer.width, layer.height, 1.0)
        mvp = proj @ model

        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uDrawAsColor"), layer.drawAsColor)
        # Uniforms
        upload_mat4(glGetUniformLocation(self.flowmapprogram, "uMVP"), mvp)
        glUniform1f(glGetUniformLocation(self.flowmapprogram, "uZ"), z)
        glUniform1f(glGetUniformLocation(self.flowmapprogram, "uOffset"), layer.offset)
        
        glUniform1f(glGetUniformLocation(self.flowmapprogram, "uAlpha"), layer.alpha)
        glUniform2f(glGetUniformLocation(self.flowmapprogram, "uPanning"),
                    layer.panning_u, layer.panning_v)
        # Farbe (Selection / Normal)
        #selection blingbling (partially gets bling bling in shader)
        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uBlingBling"), blingbling)
        glUniform1f(glGetUniformLocation(self.flowmapprogram, "uTime"), self.last_update)
        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uTex"), 0)
        if selected:
            factor = self.get_layer_color_factor_sin(layer)
            color = tuple(x * factor for x in layer.color)
            glUniform4f(glGetUniformLocation(self.flowmapprogram, "uColor"), *color, 1.0)
        else:
            glUniform4f(glGetUniformLocation(self.flowmapprogram, "uColor"), *layer.color, 1.0)
        ## Flowmap color channels
        glUniform3i(glGetUniformLocation(self.flowmapprogram, "uMaskX"), *self.ColorChannelX)
        glUniform3i(glGetUniformLocation(self.flowmapprogram, "uMaskY"), *self.ColorChannelY)

        # Flowmap-Textur
        glActiveTexture(GL_TEXTURE0)
        glBindTexture(GL_TEXTURE_2D, layer.texture)
        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uFlowmap"), 0)
        #DrawMode
        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uFlowType"), layer.rdrawmode)
        # Panner-Textur
        glActiveTexture(GL_TEXTURE1)
        glBindTexture(GL_TEXTURE_2D, layer.pannertexture)
        glUniform1i(glGetUniformLocation(self.flowmapprogram, "uPanner"), 1)
        # Quad zeichnen (genauso wie bei ImageLayer)
        glBindVertexArray(self.quadvao)
        glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, None)
        glBindVertexArray(0)

        glUseProgram(0)

    def get_layercollection_by_type(self, layertype : layertypes):
        if layertype == ImageLayer:
            return self.imagelayers
        elif layertype == PathLayer:
            return self.pathlayers
        elif layertype == PointLayer:
            return self.pointlayers
        elif layertype == FlowmapLayer:
            return self.flowmaplayers
        
    def toggle_layer_selection(self, layer_id : str, layertype : layertypes, deselectothers = True):
        collection = self.get_layercollection_by_type(layertype)
        if layer_id in collection:
            if collection[layer_id].selected:
                self.set_layer_as_deselected(layertype, layer_id)
            else:
                self.set_layer_as_selected(layertype, layer_id)
    
    def change_layer_color(self, layer_id : str, layertype : layertypes, newcolor = (0,0,0), deselectcolor = (1,1,1), changemultiple = True, deselectothers = True):
        collection = self.get_layercollection_by_type(layertype)
        lay : Union[ImageLayer, PathLayer, PointLayer, FlowmapLayer]
        for lay in collection.values():
            #print(f"layname: {lay.name}")
            if (not changemultiple and layer_id == lay.name) or (changemultiple and layer_id in lay.name):
                lay.color = newcolor
            elif deselectothers and not lay.color == deselectcolor:
                lay.color = deselectcolor

    def single_layer_selection(self, layer_id : str, layertype : layertypes, deselectothers = True):
        collection = self.get_layercollection_by_type(layertype)
        for lay in collection.values():
            if lay.name == layer_id:
                self.set_layer_as_selected(layertype, lay.name, False)
            elif deselectothers:
                self.set_layer_as_deselected(layertype, lay.name, False)
        self.update()

    def set_layer_as_selected(self, layertype : layertypes, layer_id: str, update = True):
        coll = self.get_layercollection_by_type(layertype)
        layer = coll[layer_id]
        if layer.selected:
            return False# schon selektiert
        layer.selected = True
        
        if update:
            self.update()
        return True

    def set_layer_as_deselected(self, layertype : layertypes, layer_id: str, update = True):
        coll = self.get_layercollection_by_type(layertype)
        layer = coll[layer_id]

        if not layer.selected:
            return False
        
        layer.selected = False
        if update:
            self.update()
        return True
    
    def load_image_cv2(self, filepath):
        img = cv2.imread(filepath, cv2.IMREAD_UNCHANGED)
        
        if img.dtype == np.dtype(np.uint16):
            img = img.astype(np.uint8)
        if img is None:
            raise ValueError(f"Could not load image {filepath}")

        # sicherstellen, dass 4 Kanäle
        if len(img.shape) == 2:
            if img.dtype == np.bool_:
                rimg = img.astype(np.uint8) * 255
            else:
                rimg = (img / img.max() * 255).astype(np.uint8)
            img = np.stack((rimg, rimg, rimg, rimg), axis = -1)
        elif img.shape[2] == 3:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGBA)
        elif img.shape[2] == 4:
            img = cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA)
        #h, w, _ = img.shape
        return img#, w, h

    def is_cluster_image(self, img):

        if isinstance(img, str):
            img = self.load_image_cv2(img)
            arr = np.array(img)
        elif isinstance(img, np.ndarray):
            arr = img
        else:
            arr = np.array(img)
        if len(arr.shape) == 3:
            if arr.shape[2] == 4:
                arr = arr[:,:,:3]
        unique = np.unique(arr)
        i = -1
        for j in unique:
            if j == -1: continue    #we skip -1 so we can have "alpha"
            if i == -1:
                i = j
            if not i == j:
                return False
        return True 
    
    def visualize_image_or_labels(self, filepathOrimg : str):
        if isinstance(filepathOrimg, str):
            img = self.load_image_cv2(filepathOrimg)
        elif isinstance(filepathOrimg, np.ndarray):
            img = filepathOrimg
        else:
            raise Exception(f"No valid img type {type(filepathOrimg)}")
        
        
        if self.is_cluster_image(img): #path.endswith("_Clusters.png"):
            
            arr = np.array(img)[:,:,0]
            unique_vals = np.unique(arr)
            unique_vals = unique_vals[unique_vals != -1]
            color_map = {}
            used_colors = []

            def random_color(val: int) -> tuple[int,int,int,int]:
                # Runde 1: Hue aus val, 0–359
                h = int(hashlib.md5(str(val).encode()).hexdigest(), 16) % 360
                # Runde 2+: variiere zusätzlich die Helligkeit
                cycle = val // 360
                s, v = 1.0, 1.0 - 0.2*cycle   # nächste Runde dunkler
                if v < 0.4: v = 0.9           # reset, falls zu dunkel
                runs = 0
                while True and runs < 255 ** 3:
                    runs += 1
                    r,g,b = [int(c*255) for c in colorsys.hsv_to_rgb(h/360, s, v)]
                    if not (r, g, b) in used_colors:
                        used_colors.append((r,g,b))
                        break
                return (r,g,b,255)

            for val in unique_vals:
                color_map[val] = random_color(val)
            #print(f"layerid:({layer_id}, colors:({color_map}))")
            # Jetzt ein leeres RGBA-Bild bauen
            h, w = arr.shape[0], arr.shape[1]
            colored = np.zeros((h, w, 4), dtype=np.uint8)

            for val, color in color_map.items():
                mask = (arr == val)   # shape (h, w)
                colored[mask] = color  # passt: color = (r,g,b,a)
            #mask = (arr == -1) #will be 0,0,0,0 if no mask colors it..
            #colored[mask] = 0
            return colored#, "RGBA")
        return img #Image.open(path).convert("RGBA")

    def layer_alpha_value_change(self, layertype : layertypes, layer_id, val, change_multiple = False):
        layercoll = self.get_layercollection_by_type(layertype)
        if not change_multiple:
            if layer_id in layercoll: layercoll[layer_id].alpha = val
        else:
            for layer in layercoll.keys():
                if layer_id in layer:
                    layercoll[layer].alpha = val
        self.update()

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.last_pos = event.position()

    def mouseMoveEvent(self, event):
        if event.buttons() & Qt.LeftButton:
            #dpr = self.devicePixelRatioF()                 # wichtig auf HiDPI
            cur = event.position()
            dx = cur.x() - self.last_pos.x()
            dy = cur.y() - self.last_pos.y()
            # Offset in framebuffer-pixeln (1:1 zur Mausbewegung)
            self.offset_x += dx# / self.zoom
            self.offset_y -= dy# / self.zoom #-> QWidget 0,0 is top left corner, QOpenGLWidget 0,0 is bottom left
            self.last_pos = cur      
            self.update()
            self.sync_scrollbars()

    def wheelEvent(self, event):
        delta = event.angleDelta().y() / 120
        factor = 1.1 ** delta
                                            # Qt-Y → OpenGL-Y
        mpx, mpy = event.position().x(), self.OG_OpenGL_height - event.position().y()
        
        self.set_new_offsets_from_zoomchange_and_zoom(self.zoom * factor, mpx, mpy)
        self.update()

    def init_set_zoom_ranges(self):
        if self.Scrollbar_Zoom:
            ZoomRange = 2**4-1
            self.Scrollbar_Zoom.setRange(1, int(ZoomRange*100))  # Faktor 0.01–5.0
            self.Scrollbar_Zoom.setValue(100)     # Start = 1.0
            if hasattr(self.Scrollbar_Zoom, "doubleSpinBox"):
                self.Scrollbar_Zoom.doubleSpinBox.setRange(0, ZoomRange)

    def init_set_speed_ranges(self):
        if self.Scrollbar_OverallSpeed:
            SpeedRange = 2**7-1
            self.Scrollbar_OverallSpeed.setRange(1, int(SpeedRange*100))  # Faktor 0.01–5.0
            self.Scrollbar_OverallSpeed.setValue(100)     # Start = 1.0
            if hasattr(self.Scrollbar_OverallSpeed, "doubleSpinBox"):
                self.Scrollbar_OverallSpeed.doubleSpinBox.setRange(0, SpeedRange)

    def sync_scrollbars(self, zoomchanged = False):
        #sets size and range of vertical and horizontal scrollbar
        if not hasattr(self, "img_width") or not hasattr(self, "img_height"):
            return
        vw, vh = self.OG_OpenGL_width, self.OG_OpenGL_height
        img_w, img_h = self.img_width * self.zoom, self.img_height * self.zoom

        # Horizontal
        max_w = max(0, int(img_w - vw))
        with QSignalBlocker(self.Scrollbar_Horizontal):
            if zoomchanged:
                self.Scrollbar_Horizontal.setRange(0, max_w)
                self.Scrollbar_Horizontal.setPageStep(img_w)
            self.Scrollbar_Horizontal.setValue(int(max_w + self.offset_x))

        # Vertikal
        max_h = max(0, int(img_h - vh))
        with QSignalBlocker(self.Scrollbar_Vertical):
            if zoomchanged:
                self.Scrollbar_Vertical.setRange(0, max_h)
                self.Scrollbar_Vertical.setPageStep(img_h)
            self.Scrollbar_Vertical.setValue(int(-self.offset_y))        
        self.vx0, self.vx1, self.vy0, self.vy1 = self.get_viewport_borders()  

    def on_scroll_h(self, value):
        # Wert direkt als Offset nehmen
        self.offset_x = -value
        self.vx0 = -self.offset_x / self.zoom - 20
        self.vx1 = self.vx0 + self.OG_OpenGL_width / self.zoom + 20
        self.update()

    def on_scroll_v(self, value):
        # Wert direkt als Offset nehmen        
        self.offset_y = -value
        self.vy0 = -self.offset_y / self.zoom - 20
        self.vy1 = self.vy0 + self.OG_OpenGL_height / self.zoom + 20
        self.update()
    
    def set_scrollbar_value_color(self, scrollbar, optimum : float = 1.0):
        scv = scrollbar.value() / 100
        scmax = scrollbar.maximum() / 100
        scmin = scrollbar.minimum() / 100
        if scv > optimum:
            if scmax != optimum: 
                ratio = 1 - (scmax - scv) / (scmax - optimum)
            else:
                ratio = 1 - (scmax - scv) / (scmax + 0.0001 - optimum)
        else:
            if optimum != scmin:
                ratio = (optimum - scv) / (optimum - scmin)
            else:
                ratio = (optimum - scv) / (optimum + 0.0001 - scmin)
        #print(f"scv:({scv}), rat({ratio}), scmax({scmax})")
        # 0 → grün, 1 → orange
        r = int(0 + ratio * (255-0))
        g = int(255 - ratio * (255-165))
        b = int(0 + ratio * (0-0))
        color = f"background-color: rgb({r},{g},{b});"
        scrollbar.setStyleSheet(color)

    def set_new_offsets_from_zoomchange_and_zoom(self, newzoomvalue : float, MyGLSpaceZoomPointX, MyGLSpaceZoomPointY, Update = False):
        z1 = self.zoom 
        self.zoom = newzoomvalue
        self.update_zoom_widgets()
        #Should already be in OpenGL Space
        mpx, mpy = MyGLSpaceZoomPointX, MyGLSpaceZoomPointY

        mx1 = mpx - self.offset_x 
        my1 = mpy - self.offset_y 
        mx2 = mx1 * self.zoom / z1 
        my2 = my1 * self.zoom / z1 
        #print(f"dz {round(z1 - self.zoom, 4)}, z1 {round(z1, 4)}, z2 {round(self.zoom, 4)}, mpx {round(mpx, 4)}, mx1 {round(mx1, 2)}, mx2 {round(mx2, 2)}, offset1 {round(self.offset_x, 2)}, offset2 {round(mpx - mx2, 2)}") 
        self.offset_x = mpx - mx2 
        self.offset_y = mpy - my2
        self.sync_scrollbars(zoomchanged=True)
        if Update:
            self.update()
        self.vx0, self.vx1, self.vy0, self.vy1 = self.get_viewport_borders()  

    def update_zoom_widgets(self):
        # Zoom
        with QSignalBlocker(self.Scrollbar_Zoom):
            self.Scrollbar_Zoom.setValue(int(self.zoom * 100))
            self.set_scrollbar_value_color(self.Scrollbar_Zoom)
            if hasattr(self.Scrollbar_Zoom, "doubleSpinBox"):
                with QSignalBlocker(self.Scrollbar_Zoom.doubleSpinBox):
                    self.Scrollbar_Zoom.doubleSpinBox.setValue(self.zoom)

    def on_scroll_zoom(self, value):
        # Scrollbar-Wert (z.B. 100 = 1.0) in Zoomfaktor wandeln
        self.set_new_offsets_from_zoomchange_and_zoom(value / 100, self.OG_OpenGL_width / 2, self.OG_OpenGL_height / 2)
        self.update()        

    def on_scroll_zoom_doublespinbox(self, value):
        self.set_new_offsets_from_zoomchange_and_zoom(value, self.OG_OpenGL_width / 2, self.OG_OpenGL_height / 2)
        self.update()    

    def on_scroll_speed(self, value):
        self.overallspeed = value / 100
        with QSignalBlocker(self.Scrollbar_OverallSpeed_doubleSpinBox):
            self.Scrollbar_OverallSpeed_doubleSpinBox.setValue(value / 100)
        self.set_scrollbar_value_color(self.Scrollbar_OverallSpeed, 1)

    def on_scroll_speed_doublespinbox(self, value):
        self.overallspeed = value
        self.Scrollbar_OverallSpeed.setValue(value * 100)

    # Helfer: shader compile/link
    def check_shader(self, shader):
        if not glGetShaderiv(shader, GL_COMPILE_STATUS):
            print(glGetShaderInfoLog(shader).decode())
            raise RuntimeError("Shader compile error")

    def check_program(self, prog):
        if not glGetProgramiv(prog, GL_LINK_STATUS):
            print(glGetProgramInfoLog(prog).decode())
            raise RuntimeError("Program link error")
        
    def createShaderProgram(self, vs_src, fs_src):
        vs = glCreateShader(GL_VERTEX_SHADER)
        glShaderSource(vs, vs_src)
        glCompileShader(vs)
        assert glGetShaderiv(vs, GL_COMPILE_STATUS)
        self.check_shader(vs)
        fs = glCreateShader(GL_FRAGMENT_SHADER)
        glShaderSource(fs, fs_src)
        glCompileShader(fs)
        assert glGetShaderiv(fs, GL_COMPILE_STATUS)
        self.check_shader(vs)
        program = glCreateProgram()
        glAttachShader(program, vs)
        glAttachShader(program, fs)
        glLinkProgram(program)
        assert glGetProgramiv(program, GL_LINK_STATUS)
        self.check_program(program)
        return program
        
    def get_viewport_borders(self):
        vx0 = -self.offset_x / self.zoom - 20
        vx1 = vx0 + self.OG_OpenGL_width / self.zoom + 20

        vy0 = -self.offset_y / self.zoom - 20
        vy1 = vy0 + self.OG_OpenGL_height / self.zoom + 20
        return vx0, vx1, vy0, vy1