# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ImageToFlowmapQTDUIjHNMMg.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractSpinBox, QApplication, QCheckBox,
    QComboBox, QDoubleSpinBox, QFrame, QHeaderView,
    QLabel, QLineEdit, QProgressBar, QPushButton,
    QScrollBar, QSizePolicy, QSlider, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_ImageToFlowmap(object):
    def setupUi(self, ImageToFlowmap):
        if not ImageToFlowmap.objectName():
            ImageToFlowmap.setObjectName(u"ImageToFlowmap")
        ImageToFlowmap.resize(1814, 930)
        self.Frame_Networks = QFrame(ImageToFlowmap)
        self.Frame_Networks.setObjectName(u"Frame_Networks")
        self.Frame_Networks.setGeometry(QRect(30, 480, 551, 161))
        self.Frame_Networks.setFrameShape(QFrame.Box)
        self.Frame_Networks.setFrameShadow(QFrame.Raised)
        self.Label_SelectNetwork = QLabel(self.Frame_Networks)
        self.Label_SelectNetwork.setObjectName(u"Label_SelectNetwork")
        self.Label_SelectNetwork.setGeometry(QRect(10, 10, 61, 16))
        self.table_SelectNetwork = QTableWidget(self.Frame_Networks)
        if (self.table_SelectNetwork.columnCount() < 2):
            self.table_SelectNetwork.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.table_SelectNetwork.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.table_SelectNetwork.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.table_SelectNetwork.setObjectName(u"table_SelectNetwork")
        self.table_SelectNetwork.setGeometry(QRect(10, 40, 311, 91))
        self.table_SelectNetwork.setSortingEnabled(True)
        self.table_SelectNetwork.setColumnCount(2)
        self.table_SelectNetwork.horizontalHeader().setCascadingSectionResizes(True)
        self.table_SelectNetwork.horizontalHeader().setDefaultSectionSize(150)
        self.table_SelectNetwork.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectNetwork.horizontalHeader().setStretchLastSection(True)
        self.table_SelectNetwork.verticalHeader().setStretchLastSection(False)
        self.Frame_NetworkMethod = QFrame(self.Frame_Networks)
        self.Frame_NetworkMethod.setObjectName(u"Frame_NetworkMethod")
        self.Frame_NetworkMethod.setGeometry(QRect(340, 10, 201, 80))
        self.Frame_NetworkMethod.setFrameShape(QFrame.StyledPanel)
        self.Frame_NetworkMethod.setFrameShadow(QFrame.Raised)
        self.progressBar_Network = QProgressBar(self.Frame_NetworkMethod)
        self.progressBar_Network.setObjectName(u"progressBar_Network")
        self.progressBar_Network.setGeometry(QRect(20, 50, 171, 20))
        self.progressBar_Network.setValue(0)
        self.Button_NetworkGenerateAll = QPushButton(self.Frame_NetworkMethod)
        self.Button_NetworkGenerateAll.setObjectName(u"Button_NetworkGenerateAll")
        self.Button_NetworkGenerateAll.setGeometry(QRect(20, 10, 91, 24))
        self.Button_NetworkGenerateParameters = QPushButton(self.Frame_NetworkMethod)
        self.Button_NetworkGenerateParameters.setObjectName(u"Button_NetworkGenerateParameters")
        self.Button_NetworkGenerateParameters.setGeometry(QRect(120, 10, 71, 24))
        self.Frame_NetworkAlpha = QFrame(self.Frame_Networks)
        self.Frame_NetworkAlpha.setObjectName(u"Frame_NetworkAlpha")
        self.Frame_NetworkAlpha.setGeometry(QRect(340, 90, 201, 71))
        self.Frame_NetworkAlpha.setFrameShape(QFrame.StyledPanel)
        self.Frame_NetworkAlpha.setFrameShadow(QFrame.Raised)
        self.SCRLB_NetworkAlpha = QScrollBar(self.Frame_NetworkAlpha)
        self.SCRLB_NetworkAlpha.setObjectName(u"SCRLB_NetworkAlpha")
        self.SCRLB_NetworkAlpha.setGeometry(QRect(20, 40, 160, 16))
        self.SCRLB_NetworkAlpha.setAutoFillBackground(False)
        self.SCRLB_NetworkAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_NetworkAlpha.setValue(50)
        self.SCRLB_NetworkAlpha.setOrientation(Qt.Horizontal)
        self.Label_NetworkAlpha = QLabel(self.Frame_NetworkAlpha)
        self.Label_NetworkAlpha.setObjectName(u"Label_NetworkAlpha")
        self.Label_NetworkAlpha.setGeometry(QRect(20, 10, 49, 16))
        self.Frame_SelectCluster = QFrame(ImageToFlowmap)
        self.Frame_SelectCluster.setObjectName(u"Frame_SelectCluster")
        self.Frame_SelectCluster.setGeometry(QRect(30, 310, 551, 171))
        self.Frame_SelectCluster.setFrameShape(QFrame.Box)
        self.Frame_SelectCluster.setFrameShadow(QFrame.Raised)
        self.Label_SelectClusters = QLabel(self.Frame_SelectCluster)
        self.Label_SelectClusters.setObjectName(u"Label_SelectClusters")
        self.Label_SelectClusters.setGeometry(QRect(10, 10, 71, 16))
        self.table_SelectCluster = QTableWidget(self.Frame_SelectCluster)
        if (self.table_SelectCluster.columnCount() < 2):
            self.table_SelectCluster.setColumnCount(2)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.table_SelectCluster.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.table_SelectCluster.setHorizontalHeaderItem(1, __qtablewidgetitem3)
        self.table_SelectCluster.setObjectName(u"table_SelectCluster")
        self.table_SelectCluster.setGeometry(QRect(10, 40, 311, 121))
        self.table_SelectCluster.setSortingEnabled(True)
        self.table_SelectCluster.setColumnCount(2)
        self.table_SelectCluster.horizontalHeader().setCascadingSectionResizes(True)
        self.table_SelectCluster.horizontalHeader().setDefaultSectionSize(150)
        self.table_SelectCluster.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectCluster.horizontalHeader().setStretchLastSection(True)
        self.table_SelectCluster.verticalHeader().setStretchLastSection(False)
        self.Frame_ClusterMethod = QFrame(self.Frame_SelectCluster)
        self.Frame_ClusterMethod.setObjectName(u"Frame_ClusterMethod")
        self.Frame_ClusterMethod.setGeometry(QRect(340, 10, 201, 80))
        self.Frame_ClusterMethod.setFrameShape(QFrame.StyledPanel)
        self.Frame_ClusterMethod.setFrameShadow(QFrame.Raised)
        self.Label_ClusterMethod = QLabel(self.Frame_ClusterMethod)
        self.Label_ClusterMethod.setObjectName(u"Label_ClusterMethod")
        self.Label_ClusterMethod.setGeometry(QRect(20, 0, 71, 16))
        self.progressBar_ClusterMethod = QProgressBar(self.Frame_ClusterMethod)
        self.progressBar_ClusterMethod.setObjectName(u"progressBar_ClusterMethod")
        self.progressBar_ClusterMethod.setGeometry(QRect(60, 50, 121, 23))
        self.progressBar_ClusterMethod.setValue(0)
        self.Button_ClusterMethodReload = QPushButton(self.Frame_ClusterMethod)
        self.Button_ClusterMethodReload.setObjectName(u"Button_ClusterMethodReload")
        self.Button_ClusterMethodReload.setGeometry(QRect(10, 50, 51, 24))
        self.comboBox_ClusterMethod = QComboBox(self.Frame_ClusterMethod)
        self.comboBox_ClusterMethod.setObjectName(u"comboBox_ClusterMethod")
        self.comboBox_ClusterMethod.setGeometry(QRect(20, 20, 121, 22))
        self.Button_ClusterMethodParameters = QPushButton(self.Frame_ClusterMethod)
        self.Button_ClusterMethodParameters.setObjectName(u"Button_ClusterMethodParameters")
        self.Button_ClusterMethodParameters.setGeometry(QRect(140, 20, 61, 24))
        self.Frame_ClusterAlpha = QFrame(self.Frame_SelectCluster)
        self.Frame_ClusterAlpha.setObjectName(u"Frame_ClusterAlpha")
        self.Frame_ClusterAlpha.setGeometry(QRect(340, 90, 201, 80))
        self.Frame_ClusterAlpha.setFrameShape(QFrame.StyledPanel)
        self.Frame_ClusterAlpha.setFrameShadow(QFrame.Raised)
        self.SCRLB_ClusterAlpha = QScrollBar(self.Frame_ClusterAlpha)
        self.SCRLB_ClusterAlpha.setObjectName(u"SCRLB_ClusterAlpha")
        self.SCRLB_ClusterAlpha.setGeometry(QRect(20, 50, 160, 16))
        self.SCRLB_ClusterAlpha.setAutoFillBackground(False)
        self.SCRLB_ClusterAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_ClusterAlpha.setValue(50)
        self.SCRLB_ClusterAlpha.setOrientation(Qt.Horizontal)
        self.Label_ClusterAlpha = QLabel(self.Frame_ClusterAlpha)
        self.Label_ClusterAlpha.setObjectName(u"Label_ClusterAlpha")
        self.Label_ClusterAlpha.setGeometry(QRect(20, 10, 49, 16))
        self.Frame_Junctions = QFrame(ImageToFlowmap)
        self.Frame_Junctions.setObjectName(u"Frame_Junctions")
        self.Frame_Junctions.setGeometry(QRect(30, 780, 551, 141))
        self.Frame_Junctions.setFrameShape(QFrame.Box)
        self.Frame_Junctions.setFrameShadow(QFrame.Raised)
        self.Label_SelectJunction = QLabel(self.Frame_Junctions)
        self.Label_SelectJunction.setObjectName(u"Label_SelectJunction")
        self.Label_SelectJunction.setGeometry(QRect(10, 10, 61, 16))
        self.table_SelectJunction = QTableWidget(self.Frame_Junctions)
        if (self.table_SelectJunction.columnCount() < 2):
            self.table_SelectJunction.setColumnCount(2)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.table_SelectJunction.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.table_SelectJunction.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        self.table_SelectJunction.setObjectName(u"table_SelectJunction")
        self.table_SelectJunction.setGeometry(QRect(10, 40, 311, 91))
        self.table_SelectJunction.setSortingEnabled(True)
        self.table_SelectJunction.setColumnCount(2)
        self.table_SelectJunction.horizontalHeader().setCascadingSectionResizes(True)
        self.table_SelectJunction.horizontalHeader().setDefaultSectionSize(150)
        self.table_SelectJunction.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectJunction.horizontalHeader().setStretchLastSection(True)
        self.table_SelectJunction.verticalHeader().setStretchLastSection(False)
        self.Frame_JunctionMethod = QFrame(self.Frame_Junctions)
        self.Frame_JunctionMethod.setObjectName(u"Frame_JunctionMethod")
        self.Frame_JunctionMethod.setGeometry(QRect(330, 40, 201, 91))
        self.Frame_JunctionMethod.setFrameShape(QFrame.StyledPanel)
        self.Frame_JunctionMethod.setFrameShadow(QFrame.Raised)
        self.Frame_JunctionAlpha = QFrame(self.Frame_JunctionMethod)
        self.Frame_JunctionAlpha.setObjectName(u"Frame_JunctionAlpha")
        self.Frame_JunctionAlpha.setGeometry(QRect(0, 10, 201, 61))
        self.Frame_JunctionAlpha.setFrameShape(QFrame.StyledPanel)
        self.Frame_JunctionAlpha.setFrameShadow(QFrame.Raised)
        self.SCRLB_JunctionAlpha = QScrollBar(self.Frame_JunctionAlpha)
        self.SCRLB_JunctionAlpha.setObjectName(u"SCRLB_JunctionAlpha")
        self.SCRLB_JunctionAlpha.setGeometry(QRect(20, 30, 160, 16))
        self.SCRLB_JunctionAlpha.setAutoFillBackground(False)
        self.SCRLB_JunctionAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_JunctionAlpha.setValue(50)
        self.SCRLB_JunctionAlpha.setOrientation(Qt.Horizontal)
        self.Label_JunctionAlpha = QLabel(self.Frame_JunctionAlpha)
        self.Label_JunctionAlpha.setObjectName(u"Label_JunctionAlpha")
        self.Label_JunctionAlpha.setGeometry(QRect(20, 10, 49, 16))
        self.Frame_Paths = QFrame(ImageToFlowmap)
        self.Frame_Paths.setObjectName(u"Frame_Paths")
        self.Frame_Paths.setGeometry(QRect(30, 640, 551, 141))
        self.Frame_Paths.setFrameShape(QFrame.Box)
        self.Frame_Paths.setFrameShadow(QFrame.Raised)
        self.Label_SelectPath = QLabel(self.Frame_Paths)
        self.Label_SelectPath.setObjectName(u"Label_SelectPath")
        self.Label_SelectPath.setGeometry(QRect(10, 10, 61, 16))
        self.table_SelectPath = QTableWidget(self.Frame_Paths)
        if (self.table_SelectPath.columnCount() < 3):
            self.table_SelectPath.setColumnCount(3)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.table_SelectPath.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.table_SelectPath.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.table_SelectPath.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        self.table_SelectPath.setObjectName(u"table_SelectPath")
        self.table_SelectPath.setGeometry(QRect(10, 40, 311, 91))
        self.table_SelectPath.setSortingEnabled(True)
        self.table_SelectPath.setColumnCount(3)
        self.table_SelectPath.horizontalHeader().setCascadingSectionResizes(True)
        self.table_SelectPath.horizontalHeader().setDefaultSectionSize(150)
        self.table_SelectPath.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectPath.horizontalHeader().setStretchLastSection(True)
        self.table_SelectPath.verticalHeader().setStretchLastSection(False)
        self.Frame_PathMethod = QFrame(self.Frame_Paths)
        self.Frame_PathMethod.setObjectName(u"Frame_PathMethod")
        self.Frame_PathMethod.setGeometry(QRect(340, 10, 201, 111))
        self.Frame_PathMethod.setFrameShape(QFrame.StyledPanel)
        self.Frame_PathMethod.setFrameShadow(QFrame.Raised)
        self.Frame_PathAlpha = QFrame(self.Frame_PathMethod)
        self.Frame_PathAlpha.setObjectName(u"Frame_PathAlpha")
        self.Frame_PathAlpha.setGeometry(QRect(0, 40, 201, 61))
        self.Frame_PathAlpha.setFrameShape(QFrame.StyledPanel)
        self.Frame_PathAlpha.setFrameShadow(QFrame.Raised)
        self.SCRLB_PathAlpha = QScrollBar(self.Frame_PathAlpha)
        self.SCRLB_PathAlpha.setObjectName(u"SCRLB_PathAlpha")
        self.SCRLB_PathAlpha.setGeometry(QRect(20, 30, 160, 16))
        self.SCRLB_PathAlpha.setAutoFillBackground(False)
        self.SCRLB_PathAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_PathAlpha.setValue(50)
        self.SCRLB_PathAlpha.setOrientation(Qt.Horizontal)
        self.Label_PathAlpha = QLabel(self.Frame_PathAlpha)
        self.Label_PathAlpha.setObjectName(u"Label_PathAlpha")
        self.Label_PathAlpha.setGeometry(QRect(20, 10, 49, 16))
        self.Button_PathDelete = QPushButton(self.Frame_PathMethod)
        self.Button_PathDelete.setObjectName(u"Button_PathDelete")
        self.Button_PathDelete.setGeometry(QRect(20, 10, 91, 24))
        self.frame_2 = QFrame(ImageToFlowmap)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(30, 9, 551, 301))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.Frame_SelectFolder = QFrame(self.frame_2)
        self.Frame_SelectFolder.setObjectName(u"Frame_SelectFolder")
        self.Frame_SelectFolder.setGeometry(QRect(0, 0, 341, 80))
        self.Frame_SelectFolder.setFrameShape(QFrame.StyledPanel)
        self.Frame_SelectFolder.setFrameShadow(QFrame.Raised)
        self.Button_SelectFolder = QPushButton(self.Frame_SelectFolder)
        self.Button_SelectFolder.setObjectName(u"Button_SelectFolder")
        self.Button_SelectFolder.setGeometry(QRect(240, 40, 75, 24))
        self.lineEdit_SelectFolder = QLineEdit(self.Frame_SelectFolder)
        self.lineEdit_SelectFolder.setObjectName(u"lineEdit_SelectFolder")
        self.lineEdit_SelectFolder.setGeometry(QRect(20, 40, 221, 22))
        self.Label_SelectFolder = QLabel(self.Frame_SelectFolder)
        self.Label_SelectFolder.setObjectName(u"Label_SelectFolder")
        self.Label_SelectFolder.setGeometry(QRect(10, 20, 41, 16))
        self.Frame_OverallSpeed = QFrame(self.frame_2)
        self.Frame_OverallSpeed.setObjectName(u"Frame_OverallSpeed")
        self.Frame_OverallSpeed.setGeometry(QRect(340, 130, 211, 80))
        self.Frame_OverallSpeed.setFrameShape(QFrame.StyledPanel)
        self.Frame_OverallSpeed.setFrameShadow(QFrame.Raised)
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed = QDoubleSpinBox(self.Frame_OverallSpeed)
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setObjectName(u"doubleSpinBox_SCRLB_MainImage_OverallSpeed")
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setGeometry(QRect(70, 30, 62, 22))
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setMaximum(15.000000000000000)
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setSingleStep(0.010000000000000)
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_SCRLB_MainImage_OverallSpeed.setValue(1.000000000000000)
        self.SCRLB_MainImage_OverallSpeed = QSlider(self.Frame_OverallSpeed)
        self.SCRLB_MainImage_OverallSpeed.setObjectName(u"SCRLB_MainImage_OverallSpeed")
        self.SCRLB_MainImage_OverallSpeed.setGeometry(QRect(20, 50, 160, 22))
        self.SCRLB_MainImage_OverallSpeed.setCursor(QCursor(Qt.PointingHandCursor))
        self.SCRLB_MainImage_OverallSpeed.setAutoFillBackground(False)
        self.SCRLB_MainImage_OverallSpeed.setMaximum(15)
        self.SCRLB_MainImage_OverallSpeed.setPageStep(1)
        self.SCRLB_MainImage_OverallSpeed.setValue(1)
        self.SCRLB_MainImage_OverallSpeed.setOrientation(Qt.Horizontal)
        self.SCRLB_MainImage_OverallSpeed.setInvertedAppearance(False)
        self.SCRLB_MainImage_OverallSpeed.setInvertedControls(False)
        self.Label__OverallSpeed = QLabel(self.Frame_OverallSpeed)
        self.Label__OverallSpeed.setObjectName(u"Label__OverallSpeed")
        self.Label__OverallSpeed.setGeometry(QRect(60, 10, 81, 16))
        self.Frame_SelectFiles = QFrame(self.frame_2)
        self.Frame_SelectFiles.setObjectName(u"Frame_SelectFiles")
        self.Frame_SelectFiles.setGeometry(QRect(10, 80, 331, 221))
        self.Frame_SelectFiles.setFrameShape(QFrame.WinPanel)
        self.Frame_SelectFiles.setFrameShadow(QFrame.Raised)
        self.Label_SelectFiles = QLabel(self.Frame_SelectFiles)
        self.Label_SelectFiles.setObjectName(u"Label_SelectFiles")
        self.Label_SelectFiles.setGeometry(QRect(20, 20, 71, 16))
        self.table_SelectFiles = QTableWidget(self.Frame_SelectFiles)
        if (self.table_SelectFiles.columnCount() < 2):
            self.table_SelectFiles.setColumnCount(2)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.table_SelectFiles.setHorizontalHeaderItem(0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.table_SelectFiles.setHorizontalHeaderItem(1, __qtablewidgetitem10)
        self.table_SelectFiles.setObjectName(u"table_SelectFiles")
        self.table_SelectFiles.setGeometry(QRect(10, 50, 311, 161))
        self.table_SelectFiles.setSelectionMode(QAbstractItemView.SingleSelection)
        self.table_SelectFiles.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table_SelectFiles.setSortingEnabled(True)
        self.table_SelectFiles.setColumnCount(2)
        self.table_SelectFiles.horizontalHeader().setVisible(True)
        self.table_SelectFiles.horizontalHeader().setCascadingSectionResizes(False)
        self.table_SelectFiles.horizontalHeader().setMinimumSectionSize(0)
        self.table_SelectFiles.horizontalHeader().setDefaultSectionSize(120)
        self.table_SelectFiles.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectFiles.horizontalHeader().setStretchLastSection(True)
        self.table_SelectFiles.verticalHeader().setStretchLastSection(False)
        self.Frame_BaseImgAlpha = QFrame(self.frame_2)
        self.Frame_BaseImgAlpha.setObjectName(u"Frame_BaseImgAlpha")
        self.Frame_BaseImgAlpha.setGeometry(QRect(340, 220, 201, 80))
        self.Frame_BaseImgAlpha.setFrameShape(QFrame.StyledPanel)
        self.Frame_BaseImgAlpha.setFrameShadow(QFrame.Raised)
        self.SCRLB_BaseImgAlpha = QScrollBar(self.Frame_BaseImgAlpha)
        self.SCRLB_BaseImgAlpha.setObjectName(u"SCRLB_BaseImgAlpha")
        self.SCRLB_BaseImgAlpha.setGeometry(QRect(20, 50, 160, 16))
        self.SCRLB_BaseImgAlpha.setAutoFillBackground(False)
        self.SCRLB_BaseImgAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_BaseImgAlpha.setValue(50)
        self.SCRLB_BaseImgAlpha.setOrientation(Qt.Horizontal)
        self.Label_BaseImgAlpha = QLabel(self.Frame_BaseImgAlpha)
        self.Label_BaseImgAlpha.setObjectName(u"Label_BaseImgAlpha")
        self.Label_BaseImgAlpha.setGeometry(QRect(20, 10, 49, 16))
        self.Frame_Zoom = QFrame(self.frame_2)
        self.Frame_Zoom.setObjectName(u"Frame_Zoom")
        self.Frame_Zoom.setGeometry(QRect(340, 50, 211, 80))
        self.Frame_Zoom.setFrameShape(QFrame.StyledPanel)
        self.Frame_Zoom.setFrameShadow(QFrame.Raised)
        self.doubleSpinBox_SCRLB_MainImage_Zoom = QDoubleSpinBox(self.Frame_Zoom)
        self.doubleSpinBox_SCRLB_MainImage_Zoom.setObjectName(u"doubleSpinBox_SCRLB_MainImage_Zoom")
        self.doubleSpinBox_SCRLB_MainImage_Zoom.setGeometry(QRect(70, 30, 62, 22))
        self.doubleSpinBox_SCRLB_MainImage_Zoom.setSingleStep(0.100000000000000)
        self.doubleSpinBox_SCRLB_MainImage_Zoom.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.SCRLB_MainImage_Zoom = QSlider(self.Frame_Zoom)
        self.SCRLB_MainImage_Zoom.setObjectName(u"SCRLB_MainImage_Zoom")
        self.SCRLB_MainImage_Zoom.setGeometry(QRect(20, 50, 160, 22))
        self.SCRLB_MainImage_Zoom.setCursor(QCursor(Qt.PointingHandCursor))
        self.SCRLB_MainImage_Zoom.setAutoFillBackground(False)
        self.SCRLB_MainImage_Zoom.setMaximum(15)
        self.SCRLB_MainImage_Zoom.setPageStep(1)
        self.SCRLB_MainImage_Zoom.setValue(1)
        self.SCRLB_MainImage_Zoom.setOrientation(Qt.Horizontal)
        self.SCRLB_MainImage_Zoom.setInvertedAppearance(False)
        self.SCRLB_MainImage_Zoom.setInvertedControls(False)
        self.Label_Zoom = QLabel(self.Frame_Zoom)
        self.Label_Zoom.setObjectName(u"Label_Zoom")
        self.Label_Zoom.setGeometry(QRect(80, 10, 31, 16))
        self.frame_3 = QFrame(ImageToFlowmap)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(590, 10, 1211, 911))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.Button_FlowmapGenerateAll = QPushButton(self.frame_3)
        self.Button_FlowmapGenerateAll.setObjectName(u"Button_FlowmapGenerateAll")
        self.Button_FlowmapGenerateAll.setGeometry(QRect(40, 20, 81, 24))
        self.Label_Flowmap = QLabel(self.frame_3)
        self.Label_Flowmap.setObjectName(u"Label_Flowmap")
        self.Label_Flowmap.setGeometry(QRect(20, 0, 71, 16))
        self.Button_PanningTexture = QPushButton(self.frame_3)
        self.Button_PanningTexture.setObjectName(u"Button_PanningTexture")
        self.Button_PanningTexture.setGeometry(QRect(450, 20, 75, 24))
        self.lineEdit_PanningTexture = QLineEdit(self.frame_3)
        self.lineEdit_PanningTexture.setObjectName(u"lineEdit_PanningTexture")
        self.lineEdit_PanningTexture.setGeometry(QRect(230, 20, 221, 22))
        self.Label_PanningTexture = QLabel(self.frame_3)
        self.Label_PanningTexture.setObjectName(u"Label_PanningTexture")
        self.Label_PanningTexture.setGeometry(QRect(230, 0, 91, 16))
        self.Label_Panning_X = QLabel(self.frame_3)
        self.Label_Panning_X.setObjectName(u"Label_Panning_X")
        self.Label_Panning_X.setGeometry(QRect(530, 0, 61, 20))
        self.doubleSpinBox_SCRLB_Panning_X = QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_SCRLB_Panning_X.setObjectName(u"doubleSpinBox_SCRLB_Panning_X")
        self.doubleSpinBox_SCRLB_Panning_X.setGeometry(QRect(530, 20, 62, 22))
        self.doubleSpinBox_SCRLB_Panning_X.setDecimals(6)
        self.doubleSpinBox_SCRLB_Panning_X.setMaximum(1000.000000000000000)
        self.doubleSpinBox_SCRLB_Panning_X.setSingleStep(0.100000000000000)
        self.doubleSpinBox_SCRLB_Panning_X.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_SCRLB_Panning_X.setValue(1.000000000000000)
        self.Label_Panning_Y = QLabel(self.frame_3)
        self.Label_Panning_Y.setObjectName(u"Label_Panning_Y")
        self.Label_Panning_Y.setGeometry(QRect(600, 0, 61, 20))
        self.doubleSpinBox_SCRLB_Panning_Y = QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_SCRLB_Panning_Y.setObjectName(u"doubleSpinBox_SCRLB_Panning_Y")
        self.doubleSpinBox_SCRLB_Panning_Y.setGeometry(QRect(600, 20, 62, 22))
        self.doubleSpinBox_SCRLB_Panning_Y.setDecimals(6)
        self.doubleSpinBox_SCRLB_Panning_Y.setMaximum(1000.000000000000000)
        self.doubleSpinBox_SCRLB_Panning_Y.setSingleStep(0.100000000000000)
        self.doubleSpinBox_SCRLB_Panning_Y.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_SCRLB_Panning_Y.setValue(1.000000000000000)
        self.progressBar_FlowmapGenerate = QProgressBar(self.frame_3)
        self.progressBar_FlowmapGenerate.setObjectName(u"progressBar_FlowmapGenerate")
        self.progressBar_FlowmapGenerate.setGeometry(QRect(30, 90, 231, 23))
        self.progressBar_FlowmapGenerate.setValue(0)
        self.Label_FlowmapAlpha = QLabel(self.frame_3)
        self.Label_FlowmapAlpha.setObjectName(u"Label_FlowmapAlpha")
        self.Label_FlowmapAlpha.setGeometry(QRect(720, 0, 49, 16))
        self.SCRLB_FlowmapAlpha = QScrollBar(self.frame_3)
        self.SCRLB_FlowmapAlpha.setObjectName(u"SCRLB_FlowmapAlpha")
        self.SCRLB_FlowmapAlpha.setGeometry(QRect(670, 20, 160, 16))
        self.SCRLB_FlowmapAlpha.setAutoFillBackground(False)
        self.SCRLB_FlowmapAlpha.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.SCRLB_FlowmapAlpha.setValue(50)
        self.SCRLB_FlowmapAlpha.setOrientation(Qt.Horizontal)
        self.frame = QFrame(self.frame_3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(270, 60, 941, 851))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.Frm_ProjectManager_Kalendar = QFrame(self.frame)
        self.Frm_ProjectManager_Kalendar.setObjectName(u"Frm_ProjectManager_Kalendar")
        self.Frm_ProjectManager_Kalendar.setGeometry(QRect(10, 0, 921, 841))
        self.Frm_ProjectManager_Kalendar.setFrameShape(QFrame.StyledPanel)
        self.Frm_ProjectManager_Kalendar.setFrameShadow(QFrame.Raised)
        self.RPLC_WDG_OpenGL_MainImage = QWidget(self.Frm_ProjectManager_Kalendar)
        self.RPLC_WDG_OpenGL_MainImage.setObjectName(u"RPLC_WDG_OpenGL_MainImage")
        self.RPLC_WDG_OpenGL_MainImage.setGeometry(QRect(30, 30, 881, 801))
        self.SCRLB_MainImage_Vertical = QScrollBar(self.Frm_ProjectManager_Kalendar)
        self.SCRLB_MainImage_Vertical.setObjectName(u"SCRLB_MainImage_Vertical")
        self.SCRLB_MainImage_Vertical.setGeometry(QRect(10, 30, 16, 811))
        self.SCRLB_MainImage_Vertical.setCursor(QCursor(Qt.PointingHandCursor))
        self.SCRLB_MainImage_Vertical.setOrientation(Qt.Vertical)
        self.SCRLB_MainImage_Horizontal = QScrollBar(self.Frm_ProjectManager_Kalendar)
        self.SCRLB_MainImage_Horizontal.setObjectName(u"SCRLB_MainImage_Horizontal")
        self.SCRLB_MainImage_Horizontal.setGeometry(QRect(30, 10, 1161, 16))
        self.SCRLB_MainImage_Horizontal.setCursor(QCursor(Qt.PointingHandCursor))
        self.SCRLB_MainImage_Horizontal.setOrientation(Qt.Horizontal)
        self.table_SelectFlowmap = QTableWidget(self.frame_3)
        if (self.table_SelectFlowmap.columnCount() < 3):
            self.table_SelectFlowmap.setColumnCount(3)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.table_SelectFlowmap.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.table_SelectFlowmap.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.table_SelectFlowmap.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        self.table_SelectFlowmap.setObjectName(u"table_SelectFlowmap")
        self.table_SelectFlowmap.setGeometry(QRect(10, 130, 251, 192))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_SelectFlowmap.sizePolicy().hasHeightForWidth())
        self.table_SelectFlowmap.setSizePolicy(sizePolicy)
        self.table_SelectFlowmap.setAutoScrollMargin(16)
        self.table_SelectFlowmap.setSortingEnabled(True)
        self.table_SelectFlowmap.setColumnCount(3)
        self.table_SelectFlowmap.horizontalHeader().setCascadingSectionResizes(True)
        self.table_SelectFlowmap.horizontalHeader().setMinimumSectionSize(27)
        self.table_SelectFlowmap.horizontalHeader().setDefaultSectionSize(96)
        self.table_SelectFlowmap.horizontalHeader().setProperty("showSortIndicator", True)
        self.table_SelectFlowmap.horizontalHeader().setStretchLastSection(True)
        self.table_SelectFlowmap.verticalHeader().setVisible(True)
        self.table_SelectFlowmap.verticalHeader().setStretchLastSection(False)
        self.Button_DisplayParameters = QPushButton(self.frame_3)
        self.Button_DisplayParameters.setObjectName(u"Button_DisplayParameters")
        self.Button_DisplayParameters.setGeometry(QRect(1060, 10, 131, 24))
        self.Button_FlowmapGenerateSelectedNetwork = QPushButton(self.frame_3)
        self.Button_FlowmapGenerateSelectedNetwork.setObjectName(u"Button_FlowmapGenerateSelectedNetwork")
        self.Button_FlowmapGenerateSelectedNetwork.setGeometry(QRect(40, 50, 171, 31))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Button_FlowmapGenerateSelectedNetwork.sizePolicy().hasHeightForWidth())
        self.Button_FlowmapGenerateSelectedNetwork.setSizePolicy(sizePolicy1)
        self.checkBox_DrawFlowmapColors = QCheckBox(self.frame_3)
        self.checkBox_DrawFlowmapColors.setObjectName(u"checkBox_DrawFlowmapColors")
        self.checkBox_DrawFlowmapColors.setGeometry(QRect(160, 330, 91, 20))
        self.Button_FlowmapExportFlowmaps = QPushButton(self.frame_3)
        self.Button_FlowmapExportFlowmaps.setObjectName(u"Button_FlowmapExportFlowmaps")
        self.Button_FlowmapExportFlowmaps.setGeometry(QRect(10, 330, 101, 24))
        self.Button_FlowmapGotoSaveLocation = QPushButton(self.frame_3)
        self.Button_FlowmapGotoSaveLocation.setObjectName(u"Button_FlowmapGotoSaveLocation")
        self.Button_FlowmapGotoSaveLocation.setGeometry(QRect(110, 330, 41, 24))

        self.retranslateUi(ImageToFlowmap)

        QMetaObject.connectSlotsByName(ImageToFlowmap)
    # setupUi

    def retranslateUi(self, ImageToFlowmap):
        ImageToFlowmap.setWindowTitle(QCoreApplication.translate("ImageToFlowmap", u"Image To Flowmap", None))
        self.Label_SelectNetwork.setText(QCoreApplication.translate("ImageToFlowmap", u"Networks", None))
        ___qtablewidgetitem = self.table_SelectNetwork.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("ImageToFlowmap", u"Network Name", None));
        ___qtablewidgetitem1 = self.table_SelectNetwork.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("ImageToFlowmap", u"Network ID", None));
        self.Button_NetworkGenerateAll.setText(QCoreApplication.translate("ImageToFlowmap", u"Generate All", None))
        self.Button_NetworkGenerateParameters.setText(QCoreApplication.translate("ImageToFlowmap", u"Parameter", None))
        self.Label_NetworkAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        self.Label_SelectClusters.setText(QCoreApplication.translate("ImageToFlowmap", u"Clusters", None))
        ___qtablewidgetitem2 = self.table_SelectCluster.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("ImageToFlowmap", u"Cluster Name", None));
        ___qtablewidgetitem3 = self.table_SelectCluster.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("ImageToFlowmap", u"Cluster ID", None));
        self.Label_ClusterMethod.setText(QCoreApplication.translate("ImageToFlowmap", u"Method", None))
        self.Button_ClusterMethodReload.setText(QCoreApplication.translate("ImageToFlowmap", u"Reload", None))
        self.Button_ClusterMethodParameters.setText(QCoreApplication.translate("ImageToFlowmap", u"Parameter", None))
        self.Label_ClusterAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        self.Label_SelectJunction.setText(QCoreApplication.translate("ImageToFlowmap", u"Junctions", None))
        ___qtablewidgetitem4 = self.table_SelectJunction.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("ImageToFlowmap", u"Junction Name", None));
        ___qtablewidgetitem5 = self.table_SelectJunction.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("ImageToFlowmap", u"Junction ID", None));
        self.Label_JunctionAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        self.Label_SelectPath.setText(QCoreApplication.translate("ImageToFlowmap", u"Paths", None))
        ___qtablewidgetitem6 = self.table_SelectPath.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("ImageToFlowmap", u"Path Name", None));
        ___qtablewidgetitem7 = self.table_SelectPath.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("ImageToFlowmap", u"Path Source", None));
        ___qtablewidgetitem8 = self.table_SelectPath.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("ImageToFlowmap", u"Path ID", None));
        self.Label_PathAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        self.Button_PathDelete.setText(QCoreApplication.translate("ImageToFlowmap", u"Delete Path", None))
        self.Button_SelectFolder.setText(QCoreApplication.translate("ImageToFlowmap", u"Select", None))
        self.Label_SelectFolder.setText(QCoreApplication.translate("ImageToFlowmap", u"Folder", None))
        self.Label__OverallSpeed.setText(QCoreApplication.translate("ImageToFlowmap", u"Overall Speed", None))
        self.Label_SelectFiles.setText(QCoreApplication.translate("ImageToFlowmap", u"Images", None))
        ___qtablewidgetitem9 = self.table_SelectFiles.horizontalHeaderItem(0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("ImageToFlowmap", u"File", None));
        ___qtablewidgetitem10 = self.table_SelectFiles.horizontalHeaderItem(1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("ImageToFlowmap", u"Output", None));
        self.Label_BaseImgAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        self.Label_Zoom.setText(QCoreApplication.translate("ImageToFlowmap", u"Zoom", None))
        self.Button_FlowmapGenerateAll.setText(QCoreApplication.translate("ImageToFlowmap", u"Generate All", None))
        self.Label_Flowmap.setText(QCoreApplication.translate("ImageToFlowmap", u"Flowmap", None))
        self.Button_PanningTexture.setText(QCoreApplication.translate("ImageToFlowmap", u"Select", None))
        self.Label_PanningTexture.setText(QCoreApplication.translate("ImageToFlowmap", u"Panning Texture", None))
        self.Label_Panning_X.setText(QCoreApplication.translate("ImageToFlowmap", u"Panning X", None))
        self.Label_Panning_Y.setText(QCoreApplication.translate("ImageToFlowmap", u"Panning Y", None))
        self.Label_FlowmapAlpha.setText(QCoreApplication.translate("ImageToFlowmap", u"Alpha", None))
        ___qtablewidgetitem11 = self.table_SelectFlowmap.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("ImageToFlowmap", u"Flowmap Name", None));
        ___qtablewidgetitem12 = self.table_SelectFlowmap.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("ImageToFlowmap", u"Flow Mode", None));
        ___qtablewidgetitem13 = self.table_SelectFlowmap.horizontalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("ImageToFlowmap", u"Flowmap ID", None));
        self.Button_DisplayParameters.setText(QCoreApplication.translate("ImageToFlowmap", u"Display Parameter", None))
        self.Button_FlowmapGenerateSelectedNetwork.setText(QCoreApplication.translate("ImageToFlowmap", u"Generate for selected Network", None))
        self.checkBox_DrawFlowmapColors.setText(QCoreApplication.translate("ImageToFlowmap", u"Draw Colors", None))
        self.Button_FlowmapExportFlowmaps.setText(QCoreApplication.translate("ImageToFlowmap", u"Export Flowmaps", None))
        self.Button_FlowmapGotoSaveLocation.setText(QCoreApplication.translate("ImageToFlowmap", u"Dir", None))
    # retranslateUi

